import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('comptabilité : import, partie double, CSV, contrepassation, devises et responsive',async({page})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');await page.getByRole('button',{name:'Créer un compte administrateur'}).click();await page.getByLabel('Email',{exact:false}).fill(`ledger-${Date.now()}@example.com`);await page.getByLabel('Mot de passe').fill('Test123456!');await page.getByRole('button',{name:'Créer mon compte'}).click();await expect(page.getByRole('heading',{name:'Votre activité, en un coup d’œil.'})).toBeVisible();
 await page.goto('/settings');await page.getByRole('button',{name:'Charger les données de démonstration'}).click();await expect(page.getByText('Données de démonstration enregistrées dans Firestore.')).toBeVisible();
 await page.goto('/accounting');await page.getByRole('button',{name:'Initialiser le plan de comptes'}).click();await expect(page.getByRole('button',{name:'Importer factures & paiements'})).toBeVisible();await page.getByRole('button',{name:'Importer factures & paiements'}).click();await expect(page.locator('.accounting-page').getByRole('status')).toContainText('6 écriture(s) importée(s)');await page.getByRole('button',{name:'Importer factures & paiements'}).click();await expect(page.locator('.accounting-page').getByRole('status')).toContainText('0 écriture(s) importée(s)');
 const tab=(name:string)=>page.getByRole('navigation',{name:'Sections comptables'}).getByRole('button',{name,exact:true});
 await tab('Nouvelle écriture').click();await page.getByLabel('Modèle d’écriture').selectOption('expense');await page.getByLabel('Référence de la pièce').fill('DEP-E2E');await page.getByLabel('Libellé de l’écriture').fill('Achat test comptable');await page.getByLabel('Débit ligne 1').fill('125.25');await expect(page.getByRole('button',{name:'Valider l’écriture'})).toBeDisabled();await page.getByLabel('Crédit ligne 2').fill('125.25');await page.getByRole('button',{name:'Valider l’écriture'}).click();await expect(page.locator('.accounting-entry')).toHaveCount(7);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exporter le journal CSV'}).click();const file=await download;expect(file.suggestedFilename()).toMatch(/^journal-HTG-.*\.csv$/);expect(await readFile((await file.path())!,'utf8')).toContain('DEP-E2E');
 await page.locator('.accounting-entry').filter({hasText:'DEP-E2E'}).getByRole('button',{name:/Contrepasser/}).click();await page.getByLabel('Motif de la contrepassation').fill('Annulation du test');await page.getByRole('button',{name:'Créer la contrepassation'}).click();await expect(page.locator('.accounting-entry')).toHaveCount(8);await expect(page.locator('.accounting-entry').filter({hasText:'DEP-E2E'}).first()).toContainText('Contrepassée');
 await tab('Synthèse').click();await expect(page.getByText('Journal et bilan équilibrés.')).toBeVisible();await page.getByLabel('Devise des rapports').selectOption('USD');await expect(page.getByText('0 écritures comptabilisées en USD.')).toBeVisible();await page.getByLabel('Devise des rapports').selectOption('HTG');
 await tab('Plan de comptes').click();await page.getByLabel('Code du compte').fill('607');await page.getByLabel('Intitulé du compte').fill('Achats complémentaires');await page.getByLabel('Type du compte').selectOption('expense');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByRole('row').filter({hasText:'Achats complémentaires'})).toBeVisible();
 for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});for(const name of ['Synthèse','Journal','Nouvelle écriture','Plan de comptes','Grand livre','Balance','Bilan & résultat','Clôtures','Historique']){await tab(name).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`${name} à ${width}px`).toBe(true);}}
 expect(errors).toEqual([]);
});
