import {verifyAccount} from './verify-account';
import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../functions/package.json',import.meta.url));process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';
const {initializeApp}=require('firebase-admin/app'),{getFirestore}=require('firebase-admin/firestore');const db=getFirestore(initializeApp({projectId:'demo-lokasyon'},'offline-ui'));
const base='http://127.0.0.1:4174';
async function localOperations(page:any):Promise<any[]>{return page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('lokasyon-outbox-v1',1);request.onsuccess=()=>{const db=request.result,transaction=db.transaction('operations'),read=transaction.objectStore('operations').getAll();read.onsuccess=()=>{resolve(read.result);db.close();};read.onerror=()=>reject(read.error);};request.onerror=()=>reject(request.error);}));}
test('hors connexion : redémarrage, saisies durables, synchronisation, doublons et conflits',async({page,context})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/login');await page.getByRole('button',{name:'Créer un compte administrateur'}).click();await page.getByLabel('Email',{exact:false}).fill(`offline-${Date.now()}@example.com`);await page.getByLabel('Mot de passe').fill('Test123456!');await page.getByRole('button',{name:'Créer mon compte'}).click();await verifyAccount(page);await expect(page.getByRole('heading',{name:'Votre activité, en un coup d’œil.'})).toBeVisible();await page.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
 await page.goto(base+'/settings');await page.getByLabel('Nom de l’entreprise').fill('Entreprise offline');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByText('Paramètres enregistrés.')).toBeVisible();await page.getByRole('button',{name:'Charger les données de démonstration'}).click();await expect(page.getByText('Données de démonstration enregistrées dans Firestore.')).toBeVisible();await page.goto(base+'/customers');await expect(page.getByRole('heading',{name:'Jean Pierre'})).toBeVisible();
 const initialSynced=(await localOperations(page)).filter(o=>o.status==='synced').length;await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Jean Pierre'})).toBeVisible();await expect(page.getByRole('region',{name:'Connexion et synchronisation'})).toContainText('Hors connexion');
 await page.goto(base+'/customers/new');await page.getByLabel('Prénom').fill('Offline');await page.getByLabel('Nom *',{exact:true}).fill('Client');await page.getByLabel('Téléphone *',{exact:true}).fill('+50938123456');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByText('Enregistré sur cet appareil, en attente de synchronisation. Consultez la file d’attente.')).toBeVisible();await expect(page.getByRole('button',{name:'Enregistrer',exact:true})).toBeDisabled();
 const year=new Date().getFullYear(),first=`LOC-${year}-00001`;await page.goto(base+'/rentals/'+first);await page.getByLabel('Montant en HTG').fill('100');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByText('Enregistré sur cet appareil, en attente de synchronisation. Consultez la file d’attente.')).toBeVisible();
 await page.goto(base+'/rentals/new');await page.getByLabel('Client *').selectOption({label:'Jean Pierre · CLI-00001'});await page.getByLabel('Bien *').selectOption({label:'Power Bank · 10 disponibles'});await page.getByLabel('Quantité',{exact:true}).fill('2');await page.getByLabel('Départ *').fill(`${year}-10-07T09:00`);await page.getByLabel('Retour prévu *').fill(`${year}-10-08T09:00`);await page.getByRole('button',{name:'Confirmer & générer la facture'}).click();await expect(page.getByText('Enregistré sur cet appareil, en attente de synchronisation. Consultez la file d’attente.')).toBeVisible();
 await page.goto(base+'/rentals/'+first);await page.getByRole('button',{name:'Valider le retour',exact:true}).click();await expect(page.getByText('Enregistré sur cet appareil, en attente de synchronisation. Consultez la file d’attente.')).toBeVisible();
 await page.goto(base+'/proformas/new');await page.getByLabel('Client *').selectOption('CLI-00001');await page.getByLabel('Bien *').selectOption('BIEN-00003');await page.getByLabel('Départ prévu (heure d’Haïti)').fill(`${year}-10-07T09:00`);await page.getByLabel('Retour prévu (heure d’Haïti)').fill(`${year}-10-08T09:00`);await page.getByLabel('Tarif par unité').fill('250');await page.getByRole('button',{name:'Enregistrer la pro forma'}).click();await expect(page.getByText('Enregistré sur cet appareil, en attente de synchronisation. Consultez la file d’attente.')).toBeVisible();
 let queued=await localOperations(page);expect(queued.filter(o=>o.status==='pending')).toHaveLength(5);const org=queued[0].org,payment=queued.find(o=>o.kind==='pay');expect((await db.collection(`organizations/${org}/customers`).get()).size).toBe(3);expect((await db.doc(`organizations/${org}/rentals/${first}`).get()).data().paid).toBe(5000);
 // Another device took the remaining stock during the outage.
 await db.doc(`organizations/${org}/assets/BIEN-00003`).update({available:0,status:'Loué'});await page.reload();expect((await localOperations(page)).filter(o=>o.status==='pending')).toHaveLength(5);
 await context.setOffline(false);await page.getByRole('button',{name:'File d’attente',exact:true}).click();await expect.poll(async()=>{const rows=await localOperations(page);return rows.filter(o=>o.status==='synced').length;},{timeout:30000}).toBe(initialSynced+4);await expect(page.locator('.offline-operation').filter({hasText:'Location'})).toContainText('Quantité indisponible');expect((await db.collection(`organizations/${org}/customers`).get()).size).toBe(4);expect((await db.doc(`organizations/${org}/rentals/${first}`).get()).data().paid).toBe(5100);expect((await db.collection(`organizations/${org}/rentals`).get()).size).toBe(3);
 expect((await db.doc(`organizations/${org}/rentals/${first}`).get()).data().status).toBe('Terminée');expect((await db.doc(`organizations/${org}/assets/BIEN-00001`).get()).data().available).toBe(1);expect((await db.collection(`organizations/${org}/proformas`).get()).size).toBe(1);
 // Simulate losing the acknowledgement after a committed payment; replay the same operation ID.
 await page.evaluate(op=>new Promise<void>((resolve,reject)=>{const request=indexedDB.open('lokasyon-outbox-v1',1);request.onsuccess=()=>{const database=request.result,t=database.transaction('operations','readwrite');t.objectStore('operations').put({...op,status:'pending'});t.oncomplete=()=>{database.close();resolve();};t.onerror=()=>reject(t.error);};}),payment);await page.getByRole('button',{name:'Synchroniser maintenant'}).click();await expect.poll(async()=>(await localOperations(page)).find(o=>o.id===payment.id).status).toBe('synced');expect((await db.doc(`organizations/${org}/rentals/${first}`).get()).data().paid).toBe(5100);expect((await db.collection(`organizations/${org}/payments`).get()).size).toBe(4);
 // Retry the stock conflict after correcting its cause, without entering another operation.
 await db.doc(`organizations/${org}/assets/BIEN-00003`).update({available:10,status:'Disponible'});await page.locator('.offline-operation').filter({hasText:'Quantité indisponible'}).getByRole('button',{name:'Réessayer',exact:true}).click();await expect.poll(async()=>(await localOperations(page)).filter(o=>o.status==='synced').length).toBe(initialSynced+5);expect((await db.doc(`organizations/${org}/assets/BIEN-00003`).get()).data().available).toBe(8);expect((await db.collection(`organizations/${org}/rentals`).get()).size).toBe(4);
 expect(errors).toEqual([]);
});
