import {test,expect} from '@playwright/test';
test('pro forma : stockage séparé, édition, PDF, impression, conversion et annulation',async({page})=>{
 await page.goto('/login');await page.getByRole('button',{name:'Créer un compte administrateur'}).click();await page.getByLabel('Email',{exact:false}).fill(`quote-${Date.now()}@example.com`);await page.getByLabel('Mot de passe').fill('Test123456!');await page.getByRole('button',{name:'Créer mon compte'}).click();await expect(page.getByRole('heading',{name:'Votre activité, en un coup d’œil.'})).toBeVisible();
 await page.goto('/settings');await page.getByRole('button',{name:'Charger les données de démonstration'}).click();await expect(page.getByText('Données de démonstration enregistrées dans Firestore.')).toBeVisible();
 await page.goto('/proformas/new');await page.getByLabel('Client *').selectOption('CLI-00001');await page.getByLabel('Bien *').selectOption('BIEN-00003');await page.getByLabel('Quantité *').fill('2');await page.getByLabel('Départ prévu').fill('2026-10-10T09:00');await page.getByLabel('Retour prévu').fill('2026-10-11T09:00');await page.getByLabel('Tarif par unité').fill('250');await page.getByLabel('Valable jusqu’au').fill('2099-12-31');await page.getByRole('button',{name:'Enregistrer la pro forma'}).click();await expect(page.getByRole('heading',{name:'Pro forma PF-2026-00001',level:1})).toBeVisible();
 await page.goto('/assets');await expect(page.getByRole('link').filter({has:page.getByRole('heading',{name:'Power Bank'})})).toContainText('10 / 10 disponibles');
 await page.goto('/invoices');await expect(page.locator('.payment-row')).toHaveCount(3);await page.goto('/payments');await expect(page.locator('.payment-row')).toHaveCount(3);
 await page.goto('/proformas/PF-2026-00001/edit');await page.getByLabel('Quantité *').fill('3');await page.getByRole('button',{name:'Enregistrer la pro forma'}).click();await expect(page.locator('.invoice')).toContainText('750 HTG');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Télécharger PDF'}).click();const file=await download;expect(file.suggestedFilename()).toBe('PF-2026-00001.pdf');await file.saveAs('/tmp/proforma-test.pdf');
 await page.emulateMedia({media:'print'});await expect(page.locator('.sidebar')).toBeHidden();await expect(page.locator('.invoice')).toBeVisible();await page.emulateMedia({media:'screen'});
 for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});for(const route of ['/proformas','/proformas/new','/proformas/PF-2026-00001','/proformas/PF-2026-00001/edit']){await page.goto(route);await expect(page.locator('h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`${route} at ${width}`).toBe(true);}}
 await page.goto('/proformas/PF-2026-00001');await page.getByRole('button',{name:'Marquer comme envoyée'}).click();await expect(page.locator('.eyebrow').filter({hasText:'Envoyée'})).toBeVisible();page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Convertir en location'}).click();await expect(page.getByText('LOC-2026-00004',{exact:true})).toBeVisible();
 await page.goto('/assets');await expect(page.getByRole('link').filter({has:page.getByRole('heading',{name:'Power Bank'})})).toContainText('7 / 10 disponibles');await page.goto('/payments');await expect(page.locator('.payment-row')).toHaveCount(3);await page.goto('/invoices');await expect(page.locator('.payment-row')).toHaveCount(4);
 await page.goto('/proformas/PF-2026-00001');await expect(page.getByRole('button',{name:'Convertir en location'})).toHaveCount(0);await expect(page.getByRole('link',{name:'Voir la location'})).toBeVisible();
 await page.goto('/proformas/new');await page.getByLabel('Client *').selectOption('CLI-00001');await page.getByLabel('Bien *').selectOption('BIEN-00003');await page.getByLabel('Valable jusqu’au').fill('2099-12-31');await page.getByLabel('Quantité *').fill('8');await page.getByRole('button',{name:'Enregistrer la pro forma'}).click();await page.getByRole('button',{name:'Convertir en location'}).click();await expect(page.getByRole('alert')).toContainText('Quantité indisponible');await page.getByRole('button',{name:'Annuler la pro forma'}).click();await expect(page.locator('.eyebrow').filter({hasText:'Annulée'})).toBeVisible();await expect(page.getByRole('button',{name:'Convertir en location'})).toHaveCount(0);
});
