import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../functions/package.json',import.meta.url)),sharp=require('sharp');
test('photos privées affichées dans les fiches et PDF ; purge locale sans toucher Firebase',async({page})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/login');await page.getByRole('button',{name:'Créer un compte administrateur'}).click();await page.getByLabel('Email',{exact:false}).fill(`privacy-${Date.now()}@example.com`);await page.getByLabel('Mot de passe').fill('Test123456!');await page.getByRole('button',{name:'Créer mon compte'}).click();await expect(page.getByRole('heading',{name:'Votre activité, en un coup d’œil.'})).toBeVisible();
 await page.goto('/settings');await page.getByRole('button',{name:'Charger les données de démonstration'}).click();await expect(page.getByText('Données de démonstration enregistrées dans Firestore.')).toBeVisible();const png=await sharp({create:{width:4,height:4,channels:3,background:'#1358ab'}}).png().toBuffer();await page.getByLabel('Logo', {exact:true}).setInputFiles({name:'logo.png',mimeType:'image/png',buffer:png});await expect(page.getByText('Logo enregistré.')).toBeVisible();
 await page.goto('/invoices/FAC-'+new Date().getFullYear()+'-00001');await expect(page.locator('img.invoice-logo')).toHaveAttribute('src',/^data:image\/jpeg;base64,/);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Télécharger PDF'}).click();const pdf=await download;expect(pdf.suggestedFilename()).toMatch(/\.pdf$/);await pdf.saveAs(test.info().outputPath('invoice.pdf'));
 await page.goto('/customers/CLI-00001');await page.getByLabel('Photo (JPEG/PNG, max. 5 Mo)').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:png});await expect(page.locator('img.photo-preview')).toHaveAttribute('src',/^data:image\/jpeg;base64,/);await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByRole('heading',{name:'Jean Pierre'})).toBeVisible();await expect(page.locator('.record-card img').first()).toHaveAttribute('src',/^data:image\/jpeg;base64,/);
 await page.goto('/settings');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Effacer les données locales de cet appareil'}).click();await expect(page.getByRole('heading',{name:'Heureux de vous retrouver'})).toBeVisible();expect(errors).toEqual([]);
});
test('l’effacement local refuse de perdre une saisie hors connexion',async({page,context})=>{
 await page.goto('/login');await page.getByRole('button',{name:'Créer un compte administrateur'}).click();await page.getByLabel('Email',{exact:false}).fill(`privacy-pending-${Date.now()}@example.com`);await page.getByLabel('Mot de passe').fill('Test123456!');await page.getByRole('button',{name:'Créer mon compte'}).click();await expect(page.getByRole('heading',{name:'Votre activité, en un coup d’œil.'})).toBeVisible();await page.goto('/settings');await page.getByRole('button',{name:'Charger les données de démonstration'}).click();await expect(page.getByText('Données de démonstration enregistrées dans Firestore.')).toBeVisible();
 await context.setOffline(true);await page.getByRole('link',{name:'Clients',exact:true}).first().click();await page.getByRole('link',{name:'+ Ajouter un client'}).click();await page.getByLabel('Prénom').fill('Client');await page.getByLabel('Nom *',{exact:true}).fill('Provisoire');await page.getByLabel('Téléphone *',{exact:true}).fill('+50937000000');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByText('Enregistré sur cet appareil, en attente de synchronisation. Consultez la file d’attente.')).toBeVisible();await page.getByRole('link',{name:'Paramètres',exact:true}).first().click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Effacer les données locales de cet appareil'}).click();await expect(page.getByRole('alert')).toContainText('Des saisies restent en attente');await expect(page.getByRole('heading',{name:'Paramètres'})).toBeVisible();
 const pending=await page.evaluate(()=>new Promise<number>(resolve=>{const r=indexedDB.open('lokasyon-outbox-v1',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('operations').objectStore('operations').getAll();q.onsuccess=()=>{resolve(q.result.filter(o=>o.status==='pending').length);db.close();};};}));expect(pending).toBe(1);
});
