import {test,expect} from '@playwright/test';
test('parcours Firebase : inscription, données, stock, paiement, retour, PDF et responsive',async({page})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');await page.getByRole('button',{name:'Créer un compte administrateur'}).click();await page.getByLabel('Email',{exact:false}).fill(`test-${Date.now()}@example.com`);await page.getByLabel('Mot de passe').fill('Test123456!');await page.getByRole('button',{name:'Créer mon compte'}).click();await expect(page.getByRole('heading',{name:'Votre activité, en un coup d’œil.'})).toBeVisible();
 await page.goto('/settings');await page.getByRole('button',{name:'Charger les données de démonstration'}).click();await expect(page.getByText('Données de démonstration enregistrées dans Firestore.')).toBeVisible();
 await page.goto('/customers/new');await page.getByLabel('Prénom').fill('Test');await page.getByLabel('Nom *',{exact:true}).fill('Client');await page.getByLabel('Téléphone *',{exact:true}).fill('+50938123456');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByRole('heading',{name:'Test Client'})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Test Client'})).toBeVisible();
 await page.goto('/rentals/new');await page.getByLabel('Client *').selectOption({label:'Jean Pierre · CLI-00001'});await page.getByLabel('Bien *').selectOption({label:'Power Bank · 10 disponibles'});await page.getByLabel('Quantité',{exact:true}).fill('2');await page.getByLabel('Départ *').fill('2026-10-01T09:00');await page.getByLabel('Retour prévu *').fill('2026-10-02T09:00');await page.getByLabel('Montant payé').fill('100');await page.getByRole('button',{name:'Confirmer & générer la facture'}).click();await expect(page.getByText('LOC-2026-00004',{exact:true}).first()).toBeVisible();
 await page.getByLabel('Montant en HTG').fill('200');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByText('Paiement enregistré.')).toBeVisible();
 await page.getByLabel('Retour réel').fill('2026-10-02T10:00');await page.getByLabel('Pénalité de retard').fill('50');await page.getByRole('button',{name:'Valider le retour'}).click();await expect(page.getByRole('heading',{name:'Retour enregistré'})).toBeVisible();
 await page.getByRole('link',{name:'Voir la facture'}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Télécharger PDF'}).click();expect((await download).suggestedFilename()).toBe('FAC-2026-00004.pdf');
 await page.goto('/assets');const card=page.getByRole('link').filter({has:page.getByRole('heading',{name:'Power Bank'})});await expect(card).toContainText('10 / 10 disponibles');
 for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});for(const route of ['/dashboard','/customers','/customers/new','/customers/CLI-00001','/assets','/assets/new','/assets/BIEN-00001','/categories','/rentals','/rentals/new','/rentals/LOC-2026-00004','/payments','/invoices','/invoices/FAC-2026-00004','/returns','/settings']){await page.goto(route,{waitUntil:'domcontentloaded'});await expect(page.locator('h1').first()).toBeVisible();await expect(page.getByRole('heading',{name:'Accès indisponible'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`${route} à ${width}px`).toBe(true);}}
 expect(errors).toEqual([]);
});
