import {test} from 'node:test';
import assert from 'node:assert/strict';
import {cents,defaultAccounts,validateJournalLines,validDate,dayInHaiti,invoiceLines,paymentAccount,validCurrency} from './accountingPolicy';
test('les montants sont conservés en centimes exacts',()=>{assert.equal(cents(125.25),12525);assert.equal(cents(.1+.2),30);for(const value of [-1,NaN,Infinity,1.001,'1',null])assert.throws(()=>cents(value));});
test('une écriture doit être équilibrée avec un seul sens par ligne',()=>{const lines=[{accountCode:'615',debit:125.25,credit:0},{accountCode:'531',debit:0,credit:125.25}];assert.equal(validateJournalLines(lines,defaultAccounts)[0].debit,12525);assert.throws(()=>validateJournalLines([lines[0],{...lines[1],credit:125}],defaultAccounts));assert.throws(()=>validateJournalLines([{...lines[0],credit:10},lines[1]],defaultAccounts));assert.throws(()=>validateJournalLines([{...lines[0],debit:0},lines[1]],defaultAccounts));assert.throws(()=>validateJournalLines([{...lines[0],accountCode:'999'},lines[1]],defaultAccounts));assert.throws(()=>validateJournalLines([lines[0]],defaultAccounts));});
test('les comptes désactivés ne peuvent pas recevoir de nouvelles écritures',()=>{assert.throws(()=>validateJournalLines([{accountCode:'531',debit:1,credit:0},{accountCode:'706',debit:0,credit:1}],defaultAccounts.map(a=>a.code==='531'?{...a,enabled:false}:a)));});
test('la facture distingue produits et cautions, et les ajustements restent équilibrés',()=>{let lines=validateJournalLines(invoiceLines(80000,10000),defaultAccounts);assert.deepEqual(lines.map(l=>[l.accountCode,l.debit,l.credit]),[['411',90000,0],['706',0,80000],['165',0,10000]]);lines=validateJournalLines(invoiceLines(75000,20000,80000,10000),defaultAccounts);assert.deepEqual(lines.map(l=>[l.accountCode,l.debit,l.credit]),[['411',5000,0],['706',5000,0],['165',0,10000]]);assert.deepEqual(invoiceLines(80000,10000,80000,10000),[]);});
test('les devises sont explicites et le crédit ne constitue pas un encaissement',()=>{assert.equal(validCurrency('USD'),'USD');assert.throws(()=>validCurrency('EUR'));assert.equal(paymentAccount('MonCash'),'513');assert.equal(paymentAccount('Autre'),'580');assert.throws(()=>paymentAccount('Crédit'));});
test('les dates inexistantes et futures sont refusées, en heure d’Haïti',()=>{assert.equal(validDate(dayInHaiti()),dayInHaiti());for(const value of ['2026-02-30','2099-01-01','2026-13-01','1999-12-31','2026-1-1'])assert.throws(()=>validDate(value));assert.equal(dayInHaiti('2026-01-01T02:00:00Z'),'2025-12-31');});
