import {createHash} from 'node:crypto';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore,FieldPath,type Transaction} from 'firebase-admin/firestore';
import {onCall,HttpsError,type CallableRequest} from 'firebase-functions/v2/https';
import {validId,validText} from './adminPolicy';
import {defaultAccounts,accountTypes,validateJournalLines,validAccountCode,validCurrency,validDate,cents,dayInHaiti,invoiceLines,paymentAccount,type Account,type JournalLine} from './accountingPolicy';
const options={region:'us-central1',maxInstances:5,timeoutSeconds:120};
const db=()=>getFirestore();
type Access={org:string;actor:string};
function ref(access:Access,collection:string,id:string){return db().doc(`organizations/${access.org}/${collection}/${id}`);}
async function access(request:CallableRequest):Promise<Access>{if(!request.auth)throw new HttpsError('unauthenticated','Connectez-vous pour continuer.');let org:string;try{org=validId(request.data?.org);}catch{throw new HttpsError('invalid-argument','Organisation invalide.');}const account=await getAuth().getUser(request.auth.uid);if(!account.emailVerified)throw new HttpsError('permission-denied','Confirmez votre adresse email.');if(account.disabled)throw new HttpsError('permission-denied','Compte suspendu.');return {org,actor:request.auth.uid};}
async function authorize(t:Transaction,a:Access){const [organization,member,status,site]=await t.getAll(db().doc(`organizations/${a.org}`),ref(a,'users',a.actor),db().doc(`accountStatus/${a.actor}`),db().doc('platform/settings'));if(!organization.exists||organization.data()?.status==='suspended'||member.data()?.role!=='admin'||member.data()?.disabled===true||status.data()?.disabled===true||site.data()?.maintenance===true)throw new HttpsError('permission-denied','Comptabilité réservée aux administrateurs actifs de cette entreprise.');}
function audit(t:Transaction,a:Access,action:string,target:string,details:Record<string,unknown>={}){t.create(db().collection(`organizations/${a.org}/accountingAudit`).doc(),{organizationId:a.org,actor:a.actor,action,target,details,createdAt:new Date().toISOString()});}
function input<T>(validate:()=>T):T{try{return validate();}catch(e){throw new HttpsError('invalid-argument',(e as Error).message);}}
async function chart(t:Transaction,a:Access){const docs=await t.get(db().collection(`organizations/${a.org}/accountingAccounts`));return docs.docs.map(d=>d.data() as Account);}
async function journalState(t:Transaction,a:Access,date:string){const [period,counter]=await t.getAll(ref(a,'accountingPeriods',date.slice(0,7)),ref(a,'counters','accountingJournal'));if(period.data()?.closed)throw new HttpsError('failed-precondition',`La période ${date.slice(0,7)} est clôturée.`);const n=(counter.data()?.value||0)+1;return {counter:counter.ref,value:n,id:`ECR-${date.slice(0,4)}-${String(n).padStart(5,'0')}`};}
function writeEntry(t:Transaction,a:Access,state:Awaited<ReturnType<typeof journalState>>,data:Record<string,unknown>,lines:JournalLine[]){t.create(ref(a,'accountingEntries',state.id),{...data,lines,organizationId:a.org,status:'posted',createdAt:new Date().toISOString(),createdBy:a.actor});t.set(state.counter,{organizationId:a.org,value:state.value});audit(t,a,'journal.post',state.id,{source:data.source,reference:data.reference});return state.id;}
// Diagnostic authentifié et en lecture seule, avec les mêmes contrôles que le journal.
export const accountingStatus=onCall(options,async request=>{const a=await access(request);return db().runTransaction(async t=>{await authorize(t,a);const accounts=await chart(t,a);return {available:true,version:1,region:'us-central1',initialized:accounts.length>0,accountCount:accounts.length};});});
export const accountingInitialize=onCall(options,async request=>{const a=await access(request);return db().runTransaction(async t=>{await authorize(t,a);const accounts=await chart(t,a);let added=0;for(const account of defaultAccounts)if(!accounts.some(c=>c.code===account.code)){t.create(ref(a,'accountingAccounts',account.code),{...account,organizationId:a.org,createdAt:new Date().toISOString(),createdBy:a.actor});added++;}if(added)audit(t,a,'chart.initialize','plan',{added});return {added};});});
export const accountingSaveAccount=onCall(options,async request=>{const a=await access(request),values=input(()=>{const code=validAccountCode(request.data?.code),name=validText(request.data?.name,100),type=request.data?.type;if(typeof type!=='string'||!Object.hasOwn(accountTypes,type)||typeof request.data?.enabled!=='boolean')throw new Error('Type de compte ou statut invalide.');return {code,name,type,enabled:request.data.enabled};});return db().runTransaction(async t=>{await authorize(t,a);const old=await t.get(ref(a,'accountingAccounts',values.code));const system=defaultAccounts.find(account=>account.code===values.code);if(system&&(system.type!==values.type||!values.enabled))throw new HttpsError('failed-precondition','Le type des comptes système est fixe et ils doivent rester actifs.');if(old.exists&&old.data()?.type!==values.type)throw new HttpsError('failed-precondition','Le type d’un compte existant ne peut pas être modifié.');if(old.data()?.system&&!values.enabled)throw new HttpsError('failed-precondition','Un compte système doit rester actif pour l’import.');t.set(old.ref,{...values,system:old.data()?.system||!!system,organizationId:a.org,updatedAt:new Date().toISOString(),updatedBy:a.actor},{merge:true});audit(t,a,'chart.save',values.code,{enabled:values.enabled});return {code:values.code};});});
export const accountingPost=onCall(options,async request=>{const a=await access(request),values=input(()=>({date:validDate(request.data?.date),currency:validCurrency(request.data?.currency),reference:validText(request.data?.reference,120),description:validText(request.data?.description,500),requestId:validId(request.data?.requestId)}));return db().runTransaction(async t=>{await authorize(t,a);const signature=input(()=>{if(!Array.isArray(request.data?.lines)||request.data.lines.length>30)throw new Error('Lignes invalides.');return createHash('sha256').update(JSON.stringify({date:values.date,currency:values.currency,reference:values.reference,description:values.description,lines:request.data.lines.map((l:any)=>({accountCode:validAccountCode(l.accountCode),debit:cents(l.debit),credit:cents(l.credit)}))})).digest('hex');});const marker=await t.get(ref(a,'accountingSources',`manual-${values.requestId}`));if(marker.exists){if(marker.data()?.signature!==signature)throw new HttpsError('already-exists','Cette demande a déjà enregistré une autre écriture. Rechargez le formulaire.');return {id:marker.data()!.entryId};}const accounts=await chart(t,a),lines=input(()=>validateJournalLines(request.data?.lines,accounts)),state=await journalState(t,a,values.date);const id=writeEntry(t,a,state,{date:values.date,currency:values.currency,reference:values.reference,description:values.description,source:'manual'},lines);t.create(marker.ref,{organizationId:a.org,entryId:id,source:'manual',signature});return {id};});});
export const accountingReverse=onCall(options,async request=>{const a=await access(request),values=input(()=>({id:validId(request.data?.id),date:validDate(request.data?.date),reason:validText(request.data?.reason,500)}));return db().runTransaction(async t=>{await authorize(t,a);const original=await t.get(ref(a,'accountingEntries',values.id)),entry=original.data();if(!entry)throw new HttpsError('not-found','Écriture introuvable.');if(entry.source!=='manual')throw new HttpsError('failed-precondition','Une écriture importée se corrige depuis sa pièce source, puis par synchronisation.');if(entry.reversedBy)return {id:entry.reversedBy};if(values.date<entry.date)throw new HttpsError('invalid-argument','La contrepassation doit être datée après l’écriture originale.');const state=await journalState(t,a,values.date),lines=(entry.lines as JournalLine[]).map(line=>({...line,debit:line.credit,credit:line.debit}));const id=writeEntry(t,a,state,{date:values.date,currency:entry.currency,reference:`ANN-${values.id}`,description:values.reason,source:'reversal',reverses:values.id},lines);t.update(original.ref,{reversedBy:id});audit(t,a,'journal.reverse',values.id,{reversal:id,reason:values.reason});return {id};});});
export const accountingSetPeriod=onCall(options,async request=>{const a=await access(request),values=input(()=>{const month=request.data?.month;if(typeof month!=='string'||!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||month<'2000-01'||month>dayInHaiti().slice(0,7)||typeof request.data?.closed!=='boolean')throw new Error('Période ou statut invalide.');return {month,closed:request.data.closed,reason:validText(request.data?.reason,500)};});return db().runTransaction(async t=>{await authorize(t,a);const period=await t.get(ref(a,'accountingPeriods',values.month));if(period.data()?.closed===values.closed)return {ok:true};t.set(period.ref,{organizationId:a.org,closed:values.closed,reason:values.reason,updatedAt:new Date().toISOString(),updatedBy:a.actor});audit(t,a,values.closed?'period.close':'period.reopen',values.month,{reason:values.reason});return {ok:true};});});
async function importInvoice(a:Access,id:string){return db().runTransaction(async t=>{await authorize(t,a);const invoice=await t.get(ref(a,'invoices',id));if(!invoice.exists)throw new Error('Facture introuvable.');const rentalId=validId(invoice.data()?.rentalId),rental=(await t.get(ref(a,'rentals',rentalId))).data();if(!rental)throw new Error('Location source introuvable.');const currency=validCurrency(rental.currency),revenue=cents(rental.rentalTotal),deposit=cents(rental.deposit||0);if(cents(rental.total)!==revenue+deposit)throw new Error('Total de facture incohérent.');const marker=await t.get(ref(a,'accountingSources',`invoice-${id}`)),old=marker.data();if(old&&(old.currency!==currency||old.rentalId!==rentalId))throw new Error('La devise ou la location d’une facture déjà comptabilisée a changé.');const raw=invoiceLines(revenue,deposit,old?.revenue||0,old?.deposit||0);if(old&&!raw.length)return 'unchanged';const accounts=await chart(t,a),date=validDate(old?dayInHaiti():dayInHaiti(invoice.data()?.createdAt||rental.createdAt)),state=await journalState(t,a,date);let entryId=old?.entryId||null;
 if(raw.length){const lines=validateJournalLines(raw,accounts);entryId=writeEntry(t,a,state,{date,currency,reference:id,description:`${old?'Ajustement de facture':'Facture de location'} · ${rental.customerName||rentalId}`,source:old?'adjustment':'invoice',sourceId:id,rentalId},lines);}
 t.set(marker.ref,{organizationId:a.org,source:'invoice',rentalId,currency,revenue,deposit,entryId,updatedAt:new Date().toISOString()});return old?'adjusted':raw.length?'created':'unchanged';});}
async function importPayment(a:Access,id:string){return db().runTransaction(async t=>{await authorize(t,a);const payment=(await t.get(ref(a,'payments',id))).data();if(!payment)throw new Error('Paiement introuvable.');const rentalId=validId(payment.rentalId),rental=(await t.get(ref(a,'rentals',rentalId))).data();if(!rental)throw new Error('Location source introuvable.');const currency=validCurrency(payment.currency),amount=cents(payment.amount),wallet=paymentAccount(payment.method);if(amount<=0||currency!==rental.currency)throw new Error('Montant ou devise du paiement incohérent.');const marker=await t.get(ref(a,'accountingSources',`payment-${id}`));if(marker.exists){const old=marker.data()!;if(old.amount!==amount||old.currency!==currency||old.rentalId!==rentalId||old.wallet!==wallet||old.paymentDate!==payment.date)throw new Error('Un paiement déjà comptabilisé a été modifié : passez une correction justifiée dans le journal.');return 'unchanged';}const invoice=(await t.get(ref(a,'accountingSources',`invoice-${validId(rental.invoice)}`))).data();if(!invoice)throw new Error('Comptabilisez d’abord la facture associée.');const allPayments=await t.get(db().collection(`organizations/${a.org}/payments`).where('rentalId','==',rentalId));const paid=allPayments.docs.reduce((sum,p)=>sum+cents(p.data().amount),0);if(paid>cents(rental.total))throw new Error('Les paiements dépassent le montant de la facture.');const accounts=await chart(t,a),date=validDate(dayInHaiti(payment.date)),state=await journalState(t,a,date),lines=validateJournalLines([{accountCode:wallet,debit:amount/100,credit:0},{accountCode:'411',debit:0,credit:amount/100}],accounts);const entryId=writeEntry(t,a,state,{date,currency,reference:id,description:`Encaissement · ${rental.customerName||rentalId} · ${payment.method}`,source:'payment',sourceId:id,rentalId},lines);t.create(marker.ref,{organizationId:a.org,source:'payment',entryId,amount,currency,rentalId,wallet,paymentDate:payment.date});return 'created';});}
export const accountingSync=onCall(options,async request=>{const a=await access(request),values=input(()=>{const stage=request.data?.stage;if(stage!=='invoices'&&stage!=='payments')throw new Error('Source invalide.');return {stage,cursor:request.data?.cursor?validId(request.data.cursor):''};});await db().runTransaction(t=>authorize(t,a));let query=db().collection(`organizations/${a.org}/${values.stage}`).orderBy(FieldPath.documentId()).limit(25);if(values.cursor)query=query.startAfter(values.cursor);const docs=await query.get(),result={created:0,adjusted:0,unchanged:0,errors:[] as {id:string;message:string}[],nextCursor:docs.size===25?docs.docs[docs.size-1].id:null};for(const source of docs.docs){try{const outcome=values.stage==='invoices'?await importInvoice(a,source.id):await importPayment(a,source.id);result[outcome]++;}catch(e){result.errors.push({id:source.id,message:(e as Error).message});}}return result;});
