import {Link} from 'react-router-dom';
import {Package,Users,Wallet,CalendarDays,ArrowUpRight,UserPlus,PackagePlus,CreditCard,RotateCcw,Plus} from 'lucide-react';
import {useApp} from '../contexts/AppContext';
import {money,overdue,today} from '../services/pricingService';
import {RentalRows} from './Rentals';
export function Dashboard(){const {data,settings}=useApp(),assets=data.assets||[],rentals=data.rentals||[],payments=data.payments||[],freeAssets=assets.filter(a=>['Disponible','Loué'].includes(a.status)),active=rentals.filter(r=>r.status==='Active'),late=rentals.filter(overdue),currency=settings.currency;
 const convert=(value:number,c:string)=>c===currency?value:c==='USD'?value*settings.exchange:value/settings.exchange;
 // Allocate each payment to rent first; the remainder is a held deposit, outside turnover.
 const revenue=(period:string)=>rentals.reduce((sum,r)=>{let received=0;const rows=payments.filter(p=>p.rentalId===r.id).sort((a,b)=>a.date.localeCompare(b.date));for(const p of rows){const allocated=Math.min(p.amount,Math.max(0,r.rentalTotal-received));received+=p.amount;const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Port-au-Prince',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(p.date));if(day.startsWith(period))sum+=convert(allocated,r.currency);}return sum;},0);
 const day=today(),stats=[{label:'Biens dans l’inventaire',value:assets.reduce((s,a)=>s+a.quantity,0),note:`${freeAssets.reduce((s,a)=>s+a.available,0)} disponibles`,Icon:Package},{label:'Locations actives',value:active.length,note:`${late.length} en retard`,Icon:CalendarDays},{label:'Clients',value:(data.customers||[]).length,note:'Votre clientèle',Icon:Users},{label:'Revenus du mois',value:money(revenue(day.slice(0,7)),currency),note:`Aujourd’hui : ${money(revenue(day),currency)}`,Icon:Wallet}];
 return <><div className="page-heading dashboard-heading"><div><p className="eyebrow">VUE D’ENSEMBLE</p><h1>Votre activité, en un coup d’œil.</h1><p>{new Intl.DateTimeFormat('fr-HT',{dateStyle:'full',timeZone:'America/Port-au-Prince'}).format(new Date())} · Bienvenue chez {settings.name}</p></div><Link className="primary" to="/rentals/new"><Plus size={18} aria-hidden="true"/> Nouvelle location</Link></div><div className="stats-grid">{stats.map(({label,value,note,Icon})=><section className="stat-card" key={label}><div><span>{label}</span><Icon size={20}/></div><strong>{value}</strong><small>{note}</small></section>)}</div><div className="quick-actions">{([['/customers/new','Nouveau client',UserPlus],['/assets/new','Ajouter un bien',PackagePlus],['/payments','Enregistrer un paiement',CreditCard],['/returns','Retour d’un bien',RotateCcw]] as const).map(([url,label,Icon])=><Link key={url} to={url}><Icon className="quick-action-icon" size={19} aria-hidden="true"/><span>{label}</span><ArrowUpRight className="quick-action-arrow" size={16} aria-hidden="true"/></Link>)}</div><div className="dashboard-split"><section className="panel padded stock-panel"><p className="eyebrow">INVENTAIRE</p><h2>Chaque bien à sa place</h2><div className="stock-line"><span><i className="dot green"/>Disponibles</span><strong>{freeAssets.reduce((s,a)=>s+a.available,0)}</strong></div><div className="stock-line"><span><i className="dot gold"/>Loués</span><strong>{active.reduce((s,r)=>s+r.quantity,0)}</strong></div><div className="stock-line"><span><i className="dot blue"/>Réservés</span><strong>{assets.filter(a=>a.status==='Réservé').reduce((s,a)=>s+a.available,0)}</strong></div><Link to="/assets" className="inline-link">Consulter l’inventaire →</Link></section><section className="balance-banner"><p>Restant à recevoir</p><h2>{money(rentals.reduce((s,r)=>s+convert(r.balance,r.currency),0),currency)}</h2><p>Gardez une vue claire sur vos encaissements.</p><Link to="/payments">Enregistrer un paiement <ArrowUpRight size={18}/></Link><div className="banner-decoration">◈</div></section></div>{late.length>0&&<section className="panel"><div className="section-heading"><h2><span className="dot red"/> Locations en retard <span className="badge danger">{late.length}</span></h2><Link to="/returns">Gérer les retours →</Link></div><RentalRows rows={late}/></section>}<section className="panel"><div className="section-heading"><div><h2>Dernières locations</h2><p>Les mouvements récents de votre activité.</p></div><Link to="/rentals">Tout voir →</Link></div><RentalRows rows={[...rentals].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')).slice(0,5)}/></section></>;
}
