import {useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useApp} from '../contexts/AppContext';
import {Form} from '../components/Form';
import {pay} from '../services/dataService';
import {money} from '../services/pricingService';
import {methods} from '../types';
export function Payments(){const {data,org}=useApp(),[message,setMessage]=useState('');return <><div className="page-heading"><div><p className="eyebrow">ENCAISSEMENTS</p><h1>Paiements</h1><p>Un historique complet, plusieurs paiements par location.</p></div></div><section className="panel padded"><h2>Enregistrer un paiement</h2>{message&&<p role="status" className="notice">{message}</p>}<Form fields={[{name:'rentalId',label:'Location',required:true,options:(data.rentals||[]).filter(r=>r.balance>0).map(r=>({value:r.id,label:`${r.id} · ${r.customerName} · ${money(r.balance,r.currency)}`}))},{name:'amount',label:'Montant (dans la devise de la location)',type:'number',required:true,min:.01,step:'.01'},{name:'method',label:'Mode de paiement',options:methods,value:'Cash HTG',required:true}]} onSubmit={async v=>{await pay(org,v.rentalId,v.amount,v.method);setMessage('Paiement enregistré.');}}/></section><section className="panel padded"><h2>Historique des paiements</h2>{[...(data.payments||[])].sort((a,b)=>b.date.localeCompare(a.date)).map(p=><Link className="payment-row" to={`/rentals/${p.rentalId}`} key={p.id}><div><strong>{p.id}</strong><small>{p.rentalId} · {new Date(p.date).toLocaleString('fr-HT',{timeZone:'America/Port-au-Prince'})}</small></div><span>{p.method}</span><strong>{money(p.amount,p.currency)}</strong></Link>)}{!data.payments?.length&&<p className="empty">Aucun paiement enregistré.</p>}</section></>;}
export function Invoices(){const {data}=useApp(),[q,setQ]=useState('');return <><div className="page-heading"><div><p className="eyebrow">DOCUMENTS</p><h1>Factures</h1><p>Vos factures, prêtes à imprimer ou à télécharger.</p></div></div><section className="panel padded"><input aria-label="Rechercher une facture" placeholder="Numéro de facture ou client…" value={q} onChange={e=>setQ(e.target.value)}/>{(data.invoices||[]).map(i=>({...i,r:(data.rentals||[]).find(r=>r.id===i.rentalId)})).filter(i=>i.r&&`${i.id} ${i.r.customerName}`.toLowerCase().includes(q.toLowerCase())).map(i=><Link className="payment-row" key={i.id} to={`/invoices/${i.id}`}><div><strong>{i.id}</strong><small>{i.r!.customerName}</small></div><strong>{money(i.r!.total,i.r!.currency)}</strong><span className="badge">Voir la facture →</span></Link>)}</section></>;}
export function Invoice(){const {id}=useParams(),{data,settings}=useApp(),[error,setError]=useState('');const invoice=(data.invoices||[]).find(i=>i.id===id),r=(data.rentals||[]).find(r=>r.id===invoice?.rentalId),customer=(data.customers||[]).find(c=>c.id===r?.customerId);if(!r)return <p>Facture introuvable.</p>;
 const items=[['Bien',r.assetName],['Quantité',r.quantity],['Durée',`${r.duration} ${r.unit}(s)`],['Tarif',money(r.rate,r.currency)],['Sous-total',money(r.subtotal,r.currency)],['Réduction',money(r.discount||0,r.currency)],['Frais',money(r.fees||0,r.currency)],['Pénalités',money(r.penalties||0,r.currency)],['Coût location',money(r.rentalTotal,r.currency)],['Caution (hors revenus)',money(r.deposit,r.currency)],['Total à payer',money(r.total,r.currency)],['Montant payé',money(r.paid,r.currency)],['Solde',money(r.balance,r.currency)]];
 async function pdf(){try{const {jsPDF}=await import('jspdf');const doc=new jsPDF();let y=22;const line=(text:string,size=11)=>{doc.setFontSize(size);const lines=doc.splitTextToSize(text,170);if(y+lines.length*6>275){doc.addPage();y=20;}doc.text(lines,20,y);y+=lines.length*6+3;};if(settings.logo){const image=new Image();image.crossOrigin='anonymous';image.src=settings.logo;await image.decode();doc.addImage(image,'JPEG',160,12,28,18);}line(settings.name,22);line(`${settings.address} | ${settings.phone}`);line(`WhatsApp : ${settings.whatsapp} | ${settings.email}`);line(`FACTURE ${id}`,16);line(`Date : ${new Date(r!.createdAt).toLocaleDateString('fr-HT',{timeZone:'America/Port-au-Prince'})}`);line(`Client : ${r!.customerName} | ${customer?.phone||''}`);for(const [k,v]of items)line(`${k} : ${v}`);line('Paiements');for(const p of(data.payments||[]).filter(p=>p.rentalId===r!.id))line(`${p.method} : ${money(p.amount,p.currency)} (${new Date(p.date).toLocaleDateString('fr-HT',{timeZone:'America/Port-au-Prince'})})`);line(`Notes : ${r!.notes||''}`);line(settings.terms);doc.save(`${id}.pdf`);}catch{setError('Le PDF n’a pas pu être créé. Réessayez ou utilisez Imprimer.');}}
 return <><div className="page-heading no-print"><h1>Facture</h1><div className="button-group"><button onClick={()=>window.print()}>Imprimer</button><button className="primary" onClick={pdf}>Télécharger PDF</button></div></div>{error&&<p className="error">{error}</p>}<article className="invoice panel padded"><div className="invoice-heading"><div>{settings.logo&&<img className="invoice-logo" src={settings.logo} alt="Logo"/>}<h2>{settings.name}</h2><p>{settings.address}<br/>{settings.phone} · WhatsApp {settings.whatsapp}<br/>{settings.email}</p></div><div><p className="eyebrow">FACTURE</p><h2>{id}</h2><p>{new Date(r.createdAt).toLocaleDateString('fr-HT',{timeZone:'America/Port-au-Prince'})}</p></div></div><hr/><p className="eyebrow">FACTURÉ À</p><h3>{r.customerName}</h3><p>{customer?.address} · {customer?.phone}</p>{items.map(([k,v])=><div className="summary-line" key={k}><span>{k}</span><strong>{v}</strong></div>)}<h3>Historique des paiements</h3>{(data.payments||[]).filter(p=>p.rentalId===r.id).map(p=><p key={p.id}>{p.method} · {money(p.amount,p.currency)} · {new Date(p.date).toLocaleDateString('fr-HT',{timeZone:'America/Port-au-Prince'})}</p>)}<p>{r.notes}</p><hr/><p>{settings.terms}</p></article></>;
}
