import {PrivateImage} from '../components/PrivateImage';
import {exportFile} from '../services/nativeService';
import {useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useApp} from '../contexts/AppContext';
import {Form,type Field} from '../components/Form';
import {saveProforma,changeProformaStatus} from '../services/proformaService';
import {createRental} from '../services/dataService';
import {fromHaiti,localDate} from '../services/dateService';
import {money,today} from '../services/pricingService';
import {units} from '../types';
const date=(value:string)=>new Date(value).toLocaleString('fr-HT',{timeZone:'America/Port-au-Prince'});
function inputDate(value:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Port-au-Prince',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
const status=(q:any)=>['Brouillon','Envoyée'].includes(q.status)&&q.validUntil<today()?'Expirée':q.status;
export function Proformas(){const {data}=useApp(),[search,setSearch]=useState('');return <><div className="page-heading"><div><p className="eyebrow">DOCUMENTS PRÉVISIONNELS</p><h1>Pro forma</h1><p>Préparez une proposition, puis convertissez-la en location.</p></div><Link to="/proformas/new" className="primary">+ Nouvelle pro forma</Link></div><section className="panel padded"><input aria-label="Rechercher une pro forma" placeholder="Numéro, client ou bien…" value={search} onChange={e=>setSearch(e.target.value)}/>{(data.proformas||[]).filter(q=>`${q.id} ${q.customerName} ${q.assetName}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(q=><Link className="payment-row" key={q.id} to={`/proformas/${q.id}`}><div><strong>{q.id}</strong><small>{q.customerName} · {q.assetName}</small></div><strong>{money(q.total,q.currency)}</strong><span className="badge">{status(q)}</span></Link>)}{!data.proformas?.length&&<p className="empty">Aucune pro forma. Préparez votre première proposition.</p>}</section></>;}
export function ProformaEditor(){const {id}=useParams(),{org,data,settings}=useApp(),nav=useNavigate();const q=data.proformas?.find(q=>q.id===id);if(id&&!q)return <p>Pro forma introuvable.</p>;if(q&&!['Brouillon','Envoyée'].includes(q.status))return <p>Cette pro forma ne peut plus être modifiée. <Link to={`/proformas/${id}`}>Retour</Link></p>;
 const fields:Field[]=[{name:'customerId',label:'Client',required:true,options:(data.customers||[]).map(c=>({value:c.id,label:`${c.firstName} ${c.lastName}`}))},{name:'assetId',label:'Bien',required:true,options:(data.assets||[]).map(a=>({value:a.id,label:`${a.name} · tarif indicatif ${money(a.rate,a.currency)}`}))},{name:'quantity',label:'Quantité',type:'number',required:true,min:1,step:'1',value:1},{name:'start',label:'Départ prévu (heure d’Haïti)',type:'datetime-local',required:true,value:localDate()},{name:'end',label:'Retour prévu (heure d’Haïti)',type:'datetime-local',required:true,value:localDate()},{name:'unit',label:'Unité',required:true,options:units,value:'jour'},{name:'rate',label:'Tarif par unité',type:'number',required:true,min:0,step:'.01',value:0},{name:'currency',label:'Devise',required:true,options:['HTG','USD'],value:settings.currency},{name:'discount',label:'Réduction',type:'number',min:0,step:'.01',value:0},{name:'fees',label:'Frais',type:'number',min:0,step:'.01',value:0},{name:'deposit',label:'Caution totale (hors revenus)',type:'number',min:0,step:'.01',value:0},{name:'validUntil',label:'Valable jusqu’au',type:'date',required:true,value:new Date(Date.parse(today())+30*86400000).toISOString().slice(0,10)},{name:'notes',label:'Notes',type:'textarea'}];
 return <><div className="page-heading"><div><p className="eyebrow">PROPOSITION DE LOCATION</p><h1>{id?'Modifier la pro forma':'Nouvelle pro forma'}</h1></div><Link to="/proformas">← Retour</Link></div><p className="notice">Indiquez le tarif convenu. Aucun stock n’est réservé et aucun paiement n’est enregistré. Le total calculé apparaîtra sur le document après enregistrement.</p><section className="panel padded"><Form key={id||'new'} fields={fields} initial={q?{...q,start:inputDate(q.start),end:inputDate(q.end)}:{}} label="Enregistrer la pro forma" onSubmit={async values=>{const key=await saveProforma(org,{...values,start:fromHaiti(values.start),end:fromHaiti(values.end)},settings,id);nav(`/proformas/${key}`);}}/></section></>;
}
export function ProformaDetail(){const {id}=useParams(),{org,data,settings}=useApp(),nav=useNavigate(),[error,setError]=useState(''),[busy,setBusy]=useState(false);const q=data.proformas?.find(q=>q.id===id);if(!q)return <p>Pro forma introuvable.</p>;const company=q.company,customer=q.customer,editable=['Brouillon','Envoyée'].includes(q.status);
 const items=[['Bien',q.assetName],['Quantité',q.quantity],['Départ prévu',date(q.start)],['Retour prévu',date(q.end)],['Durée',`${q.duration} ${q.unit}(s)`],['Tarif',money(q.rate,q.currency)],['Sous-total',money(q.subtotal,q.currency)],['Réduction',money(q.discount,q.currency)],['Frais',money(q.fees,q.currency)],['Coût location',money(q.rentalTotal,q.currency)],['Caution (hors revenus)',money(q.deposit,q.currency)],['Total prévisionnel',money(q.total,q.currency)]];
 async function action(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const pdf=async()=>{const {jsPDF}=await import('jspdf'),document=new jsPDF();let y=18;const line=(text:string)=>{for(const part of document.splitTextToSize(text.replace(/[\u202f\u00a0]/g,' '),175)){if(y>278){document.addPage();y=18;}document.text(part,18,y);y+=7;}};document.setFontSize(12);line(company.name);line([company.address,company.phone,company.email].filter(Boolean).join(' · '));line(`PRO FORMA ${q.id}`);line(`Émise le ${date(q.createdAt)} · Valable jusqu’au ${q.validUntil}`);line(`Client : ${q.customerName}`);line([customer.address,customer.phone].filter(Boolean).join(' · '));for(const [label,value] of items)line(`${label} : ${value}`);if(q.notes)line(`Notes : ${q.notes}`);if(company.terms)line(company.terms);line('Document prévisionnel. Ne constitue ni une facture définitive ni une réservation.');await exportFile(`${q.id}.pdf`,document.output('blob'));};
 return <><div className="page-heading no-print"><div><p className="eyebrow">{status(q)}</p><h1>Pro forma {q.id}</h1></div><div className="proforma-actions"><button disabled={busy} onClick={()=>window.print()}>Imprimer</button><button disabled={busy} className="primary" onClick={()=>action(pdf)}>Télécharger PDF</button></div></div>{error&&<p role="alert" className="error no-print">{error}</p>}<div className="proforma-actions no-print">{editable&&<><Link className="button" to={`/proformas/${q.id}/edit`}>Modifier</Link>{q.status==='Brouillon'&&<button disabled={busy} onClick={()=>action(()=>changeProformaStatus(org,q.id,'Envoyée'))}>Marquer comme envoyée</button>}<button disabled={busy} onClick={()=>{if(window.confirm('Annuler cette pro forma ? Elle ne pourra plus être modifiée.'))void action(()=>changeProformaStatus(org,q.id,'Annulée'));}}>Annuler la pro forma</button><button className="primary" disabled={busy||status(q)==='Expirée'} onClick={()=>{if(window.confirm('Confirmer la location ? Le stock sera déduit et une facture définitive sera créée, sans paiement.'))void action(async()=>{const rentalId=await createRental(org,{invoicePrefix:settings.prefix},q.id);nav(`/rentals/${rentalId}`);});}}>Convertir en location</button></>}{q.rentalId&&<Link className="primary" to={`/rentals/${q.rentalId}`}>Voir la location</Link>}<Link to="/proformas">Toutes les pro forma</Link></div><article className="invoice panel padded"><div className="invoice-top"><div><h2>{company.name}</h2><p>{company.address}</p><p>{company.phone} · {company.email}</p></div>{company.logo&&<PrivateImage src={company.logo} alt="Logo de l’entreprise" style={{maxWidth:120,maxHeight:80}}/>}</div><h2>PRO FORMA {q.id}</h2><p>Émise le {date(q.createdAt)} · Valable jusqu’au {q.validUntil} · {status(q)}</p><h3>Client : {q.customerName}</h3><p>{customer.address} · {customer.phone}</p>{items.map(([label,value])=><div className="summary-line" key={label}><span>{label}</span><strong>{value}</strong></div>)}{q.notes&&<p style={{whiteSpace:'pre-wrap'}}>Notes : {q.notes}</p>}<p>{company.terms}</p><p className="notice">Document prévisionnel : ne constitue ni une facture définitive ni une réservation. La disponibilité est vérifiée lors de la conversion en location.</p></article></>;
}
