import {PrivateImage} from '../components/PrivateImage';
import {useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useApp} from '../contexts/AppContext';
import {Form,type Field} from '../components/Form';
import {saveRow,uploadPhoto} from '../services/dataService';
import {money} from '../services/pricingService';
import {units} from '../types';
const customerFields:Field[]=[{name:'firstName',label:'Prénom',required:true},{name:'lastName',label:'Nom',required:true},{name:'phone',label:'Téléphone',type:'tel',required:true},{name:'whatsapp',label:'WhatsApp',type:'tel'},{name:'address',label:'Adresse'},{name:'commune',label:'Commune'},{name:'department',label:'Département'},{name:'cin',label:'CIN'},{name:'nif',label:'NIF'},{name:'reference',label:'Personne de référence'},{name:'referencePhone',label:'Téléphone de référence',type:'tel'},{name:'status',label:'Statut',options:['Normal','VIP','Débiteur','Blacklisté'],value:'Normal',required:true},{name:'notes',label:'Notes',type:'textarea'}];
export function Records({kind}:{kind:'customers'|'assets'|'categories'}){
 const {data,role}=useApp(),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[page,setPage]=useState(1);const title={customers:'Clients',assets:'Biens à louer',categories:'Catégories'}[kind],rows=data[kind]||[],filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())&&(!filter||r.status===filter||r.categoryId===filter));
 return <><div className="page-heading"><div><p className="eyebrow">VOTRE RÉPERTOIRE</p><h1>{title}</h1><p>{rows.length} {kind==='customers'?'clients enregistrés':kind==='assets'?'biens dans votre inventaire':'catégories personnalisées'}</p></div>{(kind!=='categories'||role==='admin')&&<Link className="primary" to={`/${kind}/new`}>+ Ajouter {kind==='customers'?'un client':kind==='assets'?'un bien':'une catégorie'}</Link>}</div><div className="panel"><div className="filters"><input aria-label={`Rechercher ${title}`} placeholder="Rechercher par nom, code, téléphone…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/>{kind!=='categories'&&<select aria-label="Filtrer" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="">Tous les {kind==='customers'?'statuts':'catégories'}</option>{(kind==='customers'?['Normal','VIP','Débiteur','Blacklisté'].map(s=>({id:s,name:s})):data.categories||[]).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>}</div><div className="record-grid">{filtered.slice((page-1)*12,page*12).map(r=><Link className="record-card" key={r.id} to={`/${kind}/${r.id}`}>{r.photo?<PrivateImage src={r.photo} alt=""/>:<div className="record-icon">{kind==='assets'?'◇':kind==='categories'?'▦':(r.firstName||'?')[0]}</div>}<div><small>{r.code||r.id}</small><h3>{r.name||`${r.firstName} ${r.lastName}`}</h3><p>{kind==='customers'?r.phone:kind==='assets'?money(r.rate,r.currency)+' / '+r.unit:'Catégorie personnalisée'}</p>{kind==='assets'&&<p>{r.available} / {r.quantity} disponibles</p>}<span className="badge">{r.status||'Active'}</span></div></Link>)}</div>{!filtered.length&&<div className="empty">Aucun résultat. Ajoutez votre premier enregistrement.</div>}<div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>Précédent</button><span>Page {page} / {Math.max(1,Math.ceil(filtered.length/12))}</span><button disabled={page*12>=filtered.length} onClick={()=>setPage(page+1)}>Suivant</button></div></div></>;
}
export function RecordForm({kind}:{kind:'customers'|'assets'|'categories'}){
 const {id}=useParams(),{org,data}=useApp(),nav=useNavigate(),[photo,setPhoto]=useState(''),[uploading,setUploading]=useState(false),[error,setError]=useState('');const row=id?(data[kind]||[]).find(r=>r.id===id):undefined;
 if(id&&!row)return <p>Enregistrement introuvable.</p>;
 const fields:Field[]=kind==='customers'?customerFields:kind==='categories'?[{name:'name',label:'Nom de la catégorie',required:true},{name:'description',label:'Description',type:'textarea'}]:[{name:'name',label:'Nom du bien',required:true},{name:'code',label:'Code interne'},{name:'categoryId',label:'Catégorie',required:true,options:(data.categories||[]).map(r=>({value:r.id,label:r.name}))},{name:'description',label:'Description',type:'textarea'},{name:'quantity',label:'Quantité totale',type:'number',min:1,step:'1',value:1,required:true},{name:'rate',label:'Tarif',type:'number',min:0,step:'.01',required:true},{name:'currency',label:'Devise',options:['HTG','USD'],value:'HTG',required:true},{name:'unit',label:'Unité de location',options:units,value:'jour',required:true},{name:'deposit',label:'Caution unitaire',type:'number',min:0,step:'.01',value:0},{name:'condition',label:'État',options:['Bon état','Usagé','Endommagé'],value:'Bon état',required:true},{name:'location',label:'Localisation'},{name:'status',label:'Statut',options:['Disponible','Loué','Réservé','Maintenance','Endommagé','Perdu','Hors service'],value:'Disponible',required:true},{name:'notes',label:'Notes',type:'textarea'}];
 return <><div className="page-heading"><div><p className="eyebrow">RÉPERTOIRE</p><h1>{id?'Modifier':'Ajouter'} {kind==='customers'?'un client':kind==='assets'?'un bien':'une catégorie'}</h1></div><Link to={`/${kind}`}>← Retour</Link></div><div className="panel padded">{kind!=='categories'&&<label className="photo-upload">Photo (JPEG/PNG, max. 5 Mo)<input type="file" accept="image/*" disabled={uploading} onChange={async e=>{if(!e.target.files?.[0])return;setUploading(true);try{setPhoto(await uploadPhoto(org,e.target.files[0]));}catch(e){setError((e as Error).message);}finally{setUploading(false);}}}/>{(photo||row?.photo)&&<PrivateImage className="photo-preview" src={photo||row?.photo} alt="Photo"/>}{uploading&&'Téléversement…'}</label>}{error&&<p className="error">{error}</p>}<Form key={id||kind} fields={fields} initial={row} onSubmit={async v=>{if(uploading)throw new Error('Attendez la fin du téléversement.');if(kind==='assets'){if(!Number.isInteger(v.quantity))throw new Error('La quantité doit être un entier.');const unavailable=row?row.quantity-row.available:0;if(v.quantity<unavailable)throw new Error('La quantité totale ne peut pas être inférieure au stock occupé.');v.available=v.quantity-unavailable;v.quarantined=row?.quarantined||0;}await saveRow(org,kind,{...v,...(photo?{photo}:{} )},id);nav(`/${kind}`);}}/></div>{id&&kind!=='categories'&&<section className="panel padded"><h2>Historique des locations</h2>{(data.rentals||[]).filter(r=>r[kind==='customers'?'customerId':'assetId']===id).map(r=><Link className="history-row" to={`/rentals/${r.id}`} key={r.id}>{r.id} · {r.assetName} · {r.status} · {money(r.balance,r.currency)}</Link>)}</section>}</>;
}
