import {Brand} from '../components/Brand';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {collection,doc,onSnapshot,query,orderBy,limit,getDocs} from 'firebase/firestore';
import {Shield,LogOut,Download} from 'lucide-react';
import {db} from '../firebase';
import {useApp} from '../contexts/AppContext';
import {Form} from '../components/Form';
import {adminCall} from '../services/adminService';
import type {Row} from '../types';
import type {Account} from '../types/platform';
const sections=[['overview','Vue globale'],['organizations','Entreprises'],['accounts','Comptes'],['settings','Paramètres du site'],['admins','Super-administrateurs'],['audit','Journal des actions']] as const;
function stamp(value:any){return value?.toDate?value.toDate().toLocaleString('fr-HT',{timeZone:'America/Port-au-Prince'}):value?new Date(value).toLocaleString('fr-HT',{timeZone:'America/Port-au-Prince'}):'—';}
function csv(name:string,rows:Record<string,unknown>[]){if(!rows.length)return;const keys=Object.keys(rows[0]);const quote=(v:unknown)=>{let text=String(v??'');if(/^\s*[=+@-]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};const blob=new Blob(['\uFEFF'+[keys.map(quote).join(';'),...rows.map(r=>keys.map(k=>quote(r[k])).join(';'))].join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function SuperAdmin(){
 const {user,site,logout}=useApp();const [section,setSection]=useState('overview'),[organizations,setOrganizations]=useState<Row[]>([]),[admins,setAdmins]=useState<Row[]>([]),[audit,setAudit]=useState<Row[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[next,setNext]=useState<string|null>(null),[search,setSearch]=useState(''),[selected,setSelected]=useState<Row|null>(null),[members,setMembers]=useState<Row[]>([]),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[resetLink,setResetLink]=useState(''),[action,setAction]=useState<{name:string;data:Record<string,unknown>;label:string}|null>(null),[count,setCount]=useState(100);
 useEffect(()=>{const stops=[onSnapshot(query(collection(db,'organizations'),orderBy('__name__'),limit(count)),s=>setOrganizations(s.docs.map(d=>({...d.data(),id:d.id} as Row))),e=>setError(e.message)),onSnapshot(collection(db,'superAdmins'),s=>setAdmins(s.docs.map(d=>({...d.data(),id:d.id} as Row))),e=>setError(e.message)),onSnapshot(query(collection(db,'adminAudit'),orderBy('createdAt','desc'),limit(100)),s=>setAudit(s.docs.map(d=>({...d.data(),id:d.id} as Row))),e=>setError(e.message))];return()=>stops.forEach(s=>s());},[count]);
 useEffect(()=>{setMembers([]);if(!selected)return;return onSnapshot(collection(db,'organizations',selected.id,'users'),s=>setMembers(s.docs.map(d=>({...d.data(),id:d.id} as Row))),e=>setError(e.message));},[selected?.id]);
 useEffect(()=>{if(section==='accounts'&&!accounts.length)void loadAccounts();},[section]);
 async function perform(name:string,data:Record<string,unknown>){setBusy(true);setError('');setMessage('');setResetLink('');try{const result=await adminCall<any>(name,data);if(result?.link)setResetLink(result.link);setMessage('Action enregistrée.');if(name==='adminSetAccountStatus')setAccounts(rows=>rows.map(a=>a.uid===data.uid?{...a,disabled:!!data.disabled}:a));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function loadAccounts(more=false){setBusy(true);setError('');try{const result=await adminCall<{accounts:Account[];pageToken:string|null}>('adminListAccounts',more&&next?{pageToken:next}:{});setAccounts(old=>more?[...old,...result.accounts]:result.accounts);setNext(result.pageToken);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const filtered=organizations.filter(o=>`${o.name} ${o.id}`.toLowerCase().includes(search.toLowerCase()));
 async function inspect(org:Row){setSelected(org);setSection('organizations');try{const company=await getDocs(collection(db,'organizations',org.id,'settings'));const settings=company.docs.find(d=>d.id==='company')?.data();if(settings)setSelected({...org,company:settings});}catch(e){setError((e as Error).message);}}
 return <div className="super-shell"><header className="super-header"><div className="brand"><Brand/> <span className="badge">Super-admin</span></div><div className="button-group"><Link className="button" to="/dashboard">Mon entreprise</Link><button onClick={logout} aria-label="Déconnexion"><LogOut size={18}/><span className="desktop">Déconnexion</span></button></div></header><main className="super-content"><div className="page-heading"><div><p className="eyebrow">ADMINISTRATION DU SITE</p><h1>Le pilotage de votre plateforme</h1><p>{user?.email} · Accès réservé aux super-administrateurs</p></div></div><nav className="super-tabs" aria-label="Sections d’administration">{sections.map(([value,label])=><button key={value} className={section===value?'selected':''} onClick={()=>{setSection(value);setSearch('');setResetLink('');}}>{label}</button>)}</nav>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}{resetLink&&<div className="panel padded"><h2>Lien de réinitialisation</h2><p>Copiez ce lien et transmettez-le au titulaire par un canal sûr. Aucun email n’a été envoyé automatiquement.</p><input aria-label="Lien de réinitialisation" readOnly value={resetLink} onFocus={e=>e.target.select()}/></div>}
 {section==='overview'&&<><div className="stats-grid">{[['Entreprises chargées',organizations.length],['Entreprises actives',organizations.filter(o=>o.status!=='suspended').length],['Entreprises suspendues',organizations.filter(o=>o.status==='suspended').length],['Super-admins actifs',admins.filter(a=>a.active).length]].map(([title,value])=><section className="stat-card" key={title}><span>{title}</span><strong>{value}</strong></section>)}</div><section className="panel padded"><h2>État du site</h2><p>Maintenance : <strong>{site.maintenance?'activée':'désactivée'}</strong> · Création d’entreprises : <strong>{site.registrationOpen?'ouverte':'fermée'}</strong></p><p>{site.message}</p><p>Les compteurs portent sur les {organizations.length} entreprises chargées. Les comptes Firebase sont consultables dans l’onglet Comptes.</p><div className="button-group"><button className="primary" disabled={busy} onClick={()=>{if(!site.supportEmail){setSection('settings');setMessage('Renseignez l’email de support et le message, puis activez le mode maintenance.');return;}setAction({name:'adminSetSite',data:{...site,maintenance:!site.maintenance},label:site.maintenance?'Remettre le site en ligne pour tous les utilisateurs.':'Activer la maintenance : les utilisateurs ordinaires seront bloqués. La console super-admin reste accessible ; les saisies hors connexion sont conservées.'});}}>{site.maintenance?'Remettre le site en ligne':'Mettre le site en maintenance'}</button><button onClick={()=>setSection('settings')}>Gérer les paramètres</button></div></section><section className="panel padded"><h2>Dernières actions</h2>{audit.slice(0,5).map(a=><div className="history-row" key={a.id}>{a.action} · {a.target}<small>{stamp(a.createdAt)}</small></div>)}{!audit.length&&<p>Aucune action d’administration enregistrée.</p>}</section></>}
 {section==='organizations'&&<><section className="panel padded"><div className="filters"><input aria-label="Rechercher une entreprise" placeholder="Nom ou identifiant de l’entreprise…" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>csv('entreprises.csv',organizations.map(o=>({id:o.id,nom:o.name,statut:o.status||'active',creation:stamp(o.createdAt)})))}><Download size={16}/> Exporter la liste chargée</button></div><div className="record-grid">{filtered.map(o=><article className="record-card" key={o.id}><div><h3>{o.name||o.id}</h3><small>{o.id}</small><p><span className={`badge ${o.status==='suspended'?'danger':''}`}>{o.status==='suspended'?'Suspendue':'Active'}</span></p><button onClick={()=>void inspect(o)}>Gérer</button></div></article>)}</div>{organizations.length===count&&<button onClick={()=>setCount(count+100)}>Charger 100 entreprises supplémentaires</button>}{!filtered.length&&<p className="empty">Aucune entreprise trouvée.</p>}</section>{selected&&<section className="panel padded"><h2>{selected.company?.name||selected.name} · Gestion de l’entreprise</h2><p>Identifiant : <code>{selected.id}</code></p>{selected.company&&<p>{selected.company.address} · {selected.company.phone} · {selected.company.email}</p>}<Form key={selected.id} fields={[{name:'status',label:'Accès à la plateforme',options:[{value:'active',label:'Active'},{value:'suspended',label:'Suspendue'}],required:true,value:selected.status||'active'},{name:'reason',label:'Motif de la modification',required:true,type:'textarea'}]} label="Modifier le statut" onSubmit={async v=>{setAction({name:'adminSetOrganization',data:{id:selected.id,...v},label:`Modifier le statut de ${selected.name||selected.id} en ${v.status}.`});}}/><h3 className="spaced">Membres de l’entreprise</h3>{members.map(m=><div className="history-row" key={m.id}>{m.email||m.id} · {m.role} · {m.disabled?'Suspendu':'Actif'}</div>)}<Form fields={[{name:'uid',label:'UID Firebase du membre',required:true},{name:'role',label:'Rôle',options:['admin','employee'],value:'employee',required:true},{name:'disabled',label:'Accès',options:[{value:'false',label:'Actif'},{value:'true',label:'Suspendu'}],value:'false',required:true}]} label="Mettre à jour le membre" onSubmit={async v=>{setAction({name:'adminSetMember',data:{org:selected.id,...v,disabled:v.disabled==='true'},label:`Modifier l’accès du membre ${v.uid}.`});}}/></section>}</>}
 {section==='accounts'&&<><section className="panel padded"><h2>Rechercher un compte par email</h2><Form fields={[{name:'email',label:'Email',type:'email',required:true}]} label="Rechercher" onSubmit={async v=>{const account=await adminCall<Account>('adminFindAccount',v);setAccounts([account]);setNext(null);}}/><button className="spaced" disabled={busy} onClick={()=>void loadAccounts()}>Actualiser la liste</button></section><section className="panel padded"><h2>Comptes Firebase Authentication</h2>{accounts.map(a=><article className="admin-account" key={a.uid}><div><h3>{a.email||a.uid}</h3><small>{a.uid}</small><p>{a.disabled?'Suspendu':'Actif'} · Email {a.emailVerified?'vérifié':'non vérifié'}<br/>Création : {stamp(a.createdAt)} · Dernière connexion : {stamp(a.lastLogin)}</p></div><div className="button-group"><button disabled={busy||a.uid===user?.uid} onClick={()=>setAction({name:'adminSetAccountStatus',data:{uid:a.uid,disabled:!a.disabled},label:`${a.disabled?'Réactiver':'Suspendre'} le compte ${a.email||a.uid}.`})}>{a.disabled?'Réactiver':'Suspendre'}</button><button disabled={busy||!a.email} onClick={()=>setAction({name:'adminPasswordReset',data:{uid:a.uid},label:`Générer un lien de réinitialisation pour ${a.email}.`})}>Réinitialiser le mot de passe</button></div></article>)}{next&&<button disabled={busy} onClick={()=>void loadAccounts(true)}>Charger 50 comptes supplémentaires</button>}{!accounts.length&&<p className="empty">Aucun compte chargé.</p>}</section></>}
 {section==='settings'&&<section className="panel padded"><h2>Paramètres publics du site</h2><Form key={JSON.stringify(site)} initial={{...site,maintenance:String(site.maintenance),registrationOpen:String(site.registrationOpen)}} fields={[{name:'name',label:'Nom du site',required:true},{name:'supportEmail',label:'Email de support',type:'email',required:true},{name:'maintenance',label:'Mode maintenance',options:[{value:'false',label:'Désactivé'},{value:'true',label:'Activé'}],required:true},{name:'registrationOpen',label:'Création de nouvelles entreprises',options:[{value:'true',label:'Ouverte'},{value:'false',label:'Fermée'}],required:true},{name:'message',label:'Annonce / message de maintenance',type:'textarea'}]} onSubmit={async v=>{setAction({name:'adminSetSite',data:{...v,maintenance:v.maintenance==='true',registrationOpen:v.registrationOpen==='true'},label:'Modifier les paramètres du site. En maintenance, les utilisateurs ordinaires ne pourront plus accéder aux données.'});}}/></section>}
 {section==='admins'&&<section className="panel padded"><h2>Super-administrateurs</h2><p>Ces comptes peuvent gérer toutes les entreprises. Votre propre rôle ne peut pas être retiré depuis cette page.</p>{admins.map(a=><div className="history-row" key={a.id}><strong>{a.email||a.id}</strong> · {a.active?'Actif':'Rôle retiré'}<small>{a.id}</small><button className="spaced" disabled={busy||a.id===user?.uid} onClick={()=>setAction({name:'adminSetSuperAdmin',data:{uid:a.id,active:!a.active},label:`${a.active?'Retirer':'Accorder'} le rôle super-admin à ${a.email||a.id}.`})}>{a.active?'Retirer le rôle':'Réactiver le rôle'}</button></div>)}<Form fields={[{name:'uid',label:'UID du compte Firebase à promouvoir',required:true}]} label="Ajouter un super-admin" onSubmit={async v=>setAction({name:'adminSetSuperAdmin',data:{uid:v.uid,active:true},label:`Accorder l’accès à toutes les entreprises au compte ${v.uid}.`})}/></section>}
 {section==='audit'&&<section className="panel padded"><h2>Journal des 100 dernières actions</h2><button onClick={()=>csv('journal-admin.csv',audit.map(a=>({date:stamp(a.createdAt),acteur:a.actor,action:a.action,cible:a.target,details:JSON.stringify(a.details)})))}>Exporter le journal chargé</button>{audit.map(a=><div className="history-row" key={a.id}><strong>{a.action}</strong> · {a.target}<small>{stamp(a.createdAt)} · Acteur : {a.actor}</small><p>{JSON.stringify(a.details)}</p></div>)}{!audit.length&&<p>Aucune action enregistrée.</p>}</section>}
 {action&&<div className="modal-backdrop"><section className="panel padded confirm-dialog" role="dialog" aria-modal="true" aria-label="Confirmer l’action"><h2>Confirmer l’action</h2><p>{action.label}</p>{action.name==='adminSetAccountStatus'?<Form fields={[{name:'reason',label:'Motif',required:true,type:'textarea'}]} label="Confirmer" onSubmit={async v=>{const pending=action;setAction(null);await perform(pending.name,{...pending.data,...v});}}/>:<button className="primary" disabled={busy} onClick={async()=>{const pending=action;setAction(null);await perform(pending.name,pending.data);}}>Confirmer</button>}<button className="spaced" onClick={()=>setAction(null)}>Annuler</button></section></div>}
 <p className="muted spaced">Les actions sont enregistrées côté serveur. Les données de location ne sont pas supprimées lors d’une suspension.</p></main></div>;
}
