import {isQueued} from '../services/offlineService';
import {useState,type FormEvent} from 'react';
export type Field={name:string;label:string;type?:string;required?:boolean;min?:number;step?:string;options?:string[]|{value:string;label:string}[];value?:any};
export function Form({fields,onSubmit,label='Enregistrer',initial={}}:{fields:Field[];onSubmit:(values:any)=>Promise<void>;label?:string;initial?:any}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[queued,setQueued]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setQueued(false);const fd=new FormData(e.currentTarget),values:any={};for(const f of fields){values[f.name]=f.type==='number'?Number(fd.get(f.name)):fd.get(f.name);}try{for(const f of fields){if(typeof values[f.name]==='string')values[f.name]=values[f.name].trim();if(f.required&&!String(values[f.name]??'').trim())throw new Error(`${f.label} est obligatoire.`);if(f.type==='tel'&&values[f.name]&&values[f.name].replace(/\D/g,'').length<8)throw new Error(`${f.label} doit contenir au moins 8 chiffres.`);}await onSubmit(values);}catch(e){setQueued(isQueued(e));setError((e as Error).message);}finally{setBusy(false);}}
 return <form onSubmit={submit} onChange={()=>{if(queued){setQueued(false);setError('');}}} className="form-grid">{fields.map(f=><label key={f.name}>{f.label}{f.required?' *':''}{f.options?<select name={f.name} defaultValue={initial[f.name]??f.value??''} required={f.required}><option value="">Choisir…</option>{f.options.map(o=><option key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} defaultValue={initial[f.name]??f.value??''}/>:<input name={f.name} type={f.type||'text'} required={f.required} min={f.min} step={f.step} defaultValue={initial[f.name]??f.value??''} pattern={f.type==='tel'?'[+0-9() .-]{8,20}':undefined}/>}</label>)}{error&&<p role={queued?"status":"alert"} className={(queued?"notice":"error")+" full"}>{error}</p>}<div className="full"><button disabled={busy||queued} className="primary">{busy?'Enregistrement…':label}</button></div></form>;
}
export function Notice({children}:{children:React.ReactNode}){return <div className="notice">{children}</div>;}
