import {exportFile} from '../services/nativeService';
import {useNetwork} from '../services/networkService';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useApp} from '../contexts/AppContext';
import {operations,type Operation} from '../services/offlineStore';
import {subscribeOffline,syncOperations,isSyncing,retryOperation,discardOperation} from '../services/offlineService';
const names:Record<string,string>={saveRow:'Enregistrement',createRental:'Location',pay:'Paiement',returnRental:'Retour',saveProforma:'Pro forma',changeProformaStatus:'Statut pro forma'};
function description(op:Operation){if(op.kind==='saveRow')return `${op.args[0]==='customers'?'Client':op.args[0]==='assets'?'Bien':'Fiche'} · ${op.args[1].name||[op.args[1].firstName,op.args[1].lastName].filter(Boolean).join(' ')||op.args[2]||''}`;if(op.kind==='createRental'||op.kind==='saveProforma')return `${op.args[0].customerId||op.args[1]||''} · ${op.args[0].assetId||''}`;return String(op.args[0]||'');}
function link(op:Operation){if(!op.result||typeof op.result!=='string')return null;const section=op.kind==='saveRow'?op.args[0]:op.kind==='createRental'?'rentals':op.kind==='saveProforma'?'proformas':null;return section?`/${section}/${op.result}`:null;}
export function OfflineStatus(){const {user,org,loading,error,accessError,site}=useApp(),[rows,setRows]=useState<Operation[]>([]),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[storageError,setStorageError]=useState('');const online=useNetwork();
 useEffect(()=>{let alive=true;const refresh=()=>{setBusy(isSyncing());void operations().then(all=>{if(alive)setRows(all.filter(o=>o.uid===user?.uid&&o.org===org).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));}).catch(e=>{if(alive)setStorageError(e.message);});};refresh();const unsubscribe=subscribeOffline(refresh);return()=>{alive=false;unsubscribe();};},[org,user?.uid]);
 useEffect(()=>{if(!online||loading||error||accessError||site.maintenance)return;const sync=()=>void syncOperations(org).catch(e=>setStorageError(e.message));sync();const interval=setInterval(sync,20000);return()=>clearInterval(interval);},[online,loading,error,accessError,site.maintenance,org,user?.uid]);
 const pending=rows.filter(r=>r.status==='pending').length,conflicts=rows.filter(r=>r.status==='conflict').length;
 async function act(fn:()=>Promise<unknown>){try{await fn();setStorageError('');}catch(e){setStorageError((e as Error).message);}}
 return <section className="offline-status no-print" aria-label="Connexion et synchronisation"><div className="offline-status-heading"><p role="status">{!online?'Hors connexion — données consultées enregistrées sur cet appareil.':busy?'Synchronisation en cours…':'Connecté'}{pending>0?` · ${pending} opération(s) en attente`:''}{conflicts>0?` · ${conflicts} opération(s) à vérifier`:''}</p><button aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Masquer la file':'File d’attente'}</button></div>{!online&&<p className="offline-help">Les saisies restent provisoires jusqu’à leur validation en ligne. Gardez l’application ouverte au retour du réseau. Les nouveaux clients et biens seront utilisables après synchronisation.</p>}{storageError&&<p role="alert" className="error">{storageError}</p>}{open&&<div><div className="offline-status-heading"><p>Opérations de ce compte, sur cet appareil</p><button disabled={!online||busy||!!accessError||site.maintenance} onClick={()=>void act(()=>syncOperations(org))}>Synchroniser maintenant</button><button disabled={!rows.length} onClick={()=>{void act(()=>exportFile('lokasyon-saisies-locales.json',new Blob([JSON.stringify(rows,null,2)],{type:'application/json'})));}}>Sauvegarder les saisies</button></div>{rows.slice(0,100).map(op=><article className="offline-operation" key={op.id}><strong>{names[op.kind]||op.kind} · {description(op)}</strong><small>{new Date(op.createdAt).toLocaleString('fr-HT')} · {op.status==='synced'?'Synchronisé':op.status==='conflict'?'À vérifier':'En attente'} · {op.id.slice(0,8)}</small>{op.error&&<p className="error">{op.error}</p>}{link(op)&&<Link to={link(op)!}>Ouvrir l’enregistrement</Link>}{op.status==='conflict'&&<div><button disabled={!online||busy} onClick={()=>void act(async()=>{await retryOperation(op);await syncOperations(org);})}>Réessayer</button><button disabled={busy} onClick={()=>{if(window.confirm('Retirer cette saisie refusée de la file locale ? Sauvegardez-la avant si nécessaire.'))void act(()=>discardOperation(op));}}>Retirer la saisie refusée</button></div>}</article>)}{!rows.length&&<p>Aucune opération dans la file locale.</p>}<p className="offline-help">Les opérations refusées restent ici. Corrigez la cause ou retirez la saisie refusée et ressaisissez-la à partir des données à jour. Une connexion et le même compte sont nécessaires pour synchroniser. La comptabilité, l’administration du site et l’envoi de photos nécessitent le réseau.</p></div>}</section>;
}
