import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../functions/package.json',import.meta.url));
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';
const {initializeApp}=require('firebase-admin/app'),{getAuth}=require('firebase-admin/auth'),{getFirestore}=require('firebase-admin/firestore');initializeApp({projectId:'demo-lokasyon'});const auth=getAuth(),db=getFirestore();
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Port-au-Prince',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function account(label){const email=`accounting-${label}-${Date.now()}@example.com`,u=await auth.createUser({email,emailVerified:true,password:'Test123456!'});const r=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=demo-key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password:'Test123456!',returnSecureToken:true})});const body=await r.json();assert(body.idToken);return {...u,token:body.idToken};}
async function call(name,token,data={}){const r=await fetch(`http://127.0.0.1:5001/demo-lokasyon/us-central1/${name}`,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({data})});return {status:r.status,body:await r.json()};}
async function success(name,user,data){const r=await call(name,user.token,data);assert.equal(r.status,200,JSON.stringify(r.body));return r.body.result;}
test('comptabilité serveur : accès, équilibres, imports idempotents, corrections et clôtures',async()=>{
 const owner=await account('owner'),employee=await account('employee'),other=await account('other'),org=owner.uid;
 await db.doc('platform/settings').set({maintenance:false,registrationOpen:true},{merge:true});for(const u of [owner,other]){await db.doc(`organizations/${u.uid}`).set({organizationId:u.uid,name:'Test comptabilité',status:'active'});await db.doc(`organizations/${u.uid}/users/${u.uid}`).set({organizationId:u.uid,role:'admin',email:u.email});}await db.doc(`organizations/${org}/users/${employee.uid}`).set({organizationId:org,role:'employee',email:employee.email});
 assert.equal((await call('accountingInitialize',null,{org})).body.error.status,'UNAUTHENTICATED');for(const name of ['accountingInitialize','accountingPost','accountingSync','accountingSaveAccount','accountingReverse','accountingSetPeriod'])assert.equal((await call(name,employee.token,{org,stage:'invoices',code:'999',name:'Compte',type:'expense',enabled:true,id:'test-entry',date:today(),currency:'HTG',reference:'Test',description:'Test',requestId:'employee-request',lines:[{accountCode:'531',debit:1,credit:0},{accountCode:'101',debit:0,credit:1}],month:today().slice(0,7),closed:true,reason:'Test'})).body.error.status,'PERMISSION_DENIED');assert.equal((await call('accountingInitialize',other.token,{org})).body.error.status,'PERMISSION_DENIED');
 assert((await success('accountingInitialize',owner,{org})).added>20);assert.equal((await success('accountingInitialize',owner,{org})).added,0);
 assert.equal((await call('accountingSaveAccount',owner.token,{org,code:'706',name:'Intrusion',type:'asset',enabled:true})).body.error.status,'FAILED_PRECONDITION');assert.equal((await call('accountingSaveAccount',owner.token,{org,code:'999',name:'Compte',type:'__proto__',enabled:true})).body.error.status,'INVALID_ARGUMENT');await success('accountingSaveAccount',owner,{org,code:'607',name:'Autres achats',type:'expense',enabled:true});
 const root=db.collection(`organizations/${org}/accountingEntries`),now=new Date().toISOString();await db.doc(`organizations/${org}/rentals/LOC-test`).set({organizationId:org,rentalTotal:800,deposit:100,total:900,currency:'HTG',invoice:'FAC-test',createdAt:now,customerName:'Client comptable'});await db.doc(`organizations/${org}/invoices/FAC-test`).set({organizationId:org,rentalId:'LOC-test',createdAt:now});await db.doc(`organizations/${org}/payments/PAY-test`).set({organizationId:org,rentalId:'LOC-test',amount:300,currency:'HTG',method:'Cash HTG',date:now});
 assert.equal((await success('accountingSync',owner,{org,stage:'invoices'})).created,1);assert.equal((await success('accountingSync',owner,{org,stage:'invoices'})).unchanged,1);assert.equal((await success('accountingSync',owner,{org,stage:'payments'})).created,1);assert.equal((await success('accountingSync',owner,{org,stage:'payments'})).unchanged,1);assert.equal((await root.get()).size,2);
 const initial=(await root.get()).docs.map(d=>d.data());const invoice=initial.find(e=>e.source==='invoice');assert.deepEqual(invoice.lines.map(l=>[l.accountCode,l.debit,l.credit]),[['411',90000,0],['706',0,80000],['165',0,10000]]);
 await db.doc(`organizations/${org}/rentals/LOC-test`).update({rentalTotal:850,total:950});assert.equal((await success('accountingSync',owner,{org,stage:'invoices'})).adjusted,1);assert.equal((await success('accountingSync',owner,{org,stage:'invoices'})).unchanged,1);
 await db.doc(`organizations/${org}/payments/PAY-test`).update({amount:350});assert.equal((await success('accountingSync',owner,{org,stage:'payments'})).errors.length,1);await db.doc(`organizations/${org}/payments/PAY-test`).update({amount:300});
 const values={org,date:today(),currency:'HTG',reference:'DEP-test',description:'Réparation',requestId:'integration-request',lines:[{accountCode:'615',debit:125.25,credit:0},{accountCode:'531',debit:0,credit:125.25}]};
 assert.equal((await call('accountingPost',owner.token,{...values,requestId:'unbalanced',lines:[values.lines[0],{...values.lines[1],credit:125}]})).body.error.status,'INVALID_ARGUMENT');const replies=await Promise.all([success('accountingPost',owner,values),success('accountingPost',owner,values)]);assert.equal(replies[0].id,replies[1].id);assert.equal((await root.get()).size,4);assert.equal((await call('accountingPost',owner.token,{...values,description:'Texte différent'})).body.error.status,'ALREADY_EXISTS');
 const reverse=await success('accountingReverse',owner,{org,id:replies[0].id,date:today(),reason:'Correction du reçu'});assert.equal((await success('accountingReverse',owner,{org,id:replies[0].id,date:today(),reason:'Même correction'})).id,reverse.id);assert.equal((await root.doc(replies[0].id).get()).data().reversedBy,reverse.id);const imported=(await root.where('source','==','invoice').get()).docs[0];assert.equal((await call('accountingReverse',owner.token,{org,id:imported.id,date:today(),reason:'Essai'})).body.error.status,'FAILED_PRECONDITION');
 await success('accountingSetPeriod',owner,{org,month:today().slice(0,7),closed:true,reason:'Clôture contrôlée'});assert.equal((await call('accountingPost',owner.token,{...values,requestId:'closed-month'})).body.error.status,'FAILED_PRECONDITION');await db.doc(`organizations/${org}/rentals/LOC-test`).update({rentalTotal:900,total:1000});assert.equal((await success('accountingSync',owner,{org,stage:'invoices'})).errors.length,1);await success('accountingSetPeriod',owner,{org,month:today().slice(0,7),closed:false,reason:'Réouverture autorisée'});assert.equal((await success('accountingSync',owner,{org,stage:'invoices'})).adjusted,1);
 for(const doc of (await root.get()).docs){const e=doc.data();assert.equal(e.lines.reduce((n,l)=>n+l.debit,0),e.lines.reduce((n,l)=>n+l.credit,0));assert(e.lines.every(l=>Number.isSafeInteger(l.debit)&&Number.isSafeInteger(l.credit)));}assert((await db.collection(`organizations/${org}/accountingAudit`).get()).size>=10);
 await db.doc(`accountStatus/${owner.uid}`).set({disabled:true});assert.equal((await call('accountingInitialize',owner.token,{org})).body.error.status,'PERMISSION_DENIED');await db.doc(`accountStatus/${owner.uid}`).set({disabled:false});await db.doc(`organizations/${org}`).update({status:'suspended'});assert.equal((await call('accountingInitialize',owner.token,{org})).body.error.status,'PERMISSION_DENIED');await db.doc(`organizations/${org}`).update({status:'active'});
});
