import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../../functions/package.json',import.meta.url));
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.STORAGE_EMULATOR_HOST='http://127.0.0.1:9199';
const {initializeApp}=require('firebase-admin/app'),{getAuth}=require('firebase-admin/auth'),{getFirestore}=require('firebase-admin/firestore'),{getStorage}=require('firebase-admin/storage'),sharp=require('sharp');
initializeApp({projectId:'demo-lokasyon',storageBucket:'demo-lokasyon.appspot.com'});const db=getFirestore(),auth=getAuth();
async function account(label){const email=`repair-${label}-${Date.now()}@example.com`,user=await auth.createUser({email,password:'Test123456!'});const response=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=demo-key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password:'Test123456!',returnSecureToken:true})});return {...user,token:(await response.json()).idToken};}
async function call(name,user,data){const r=await fetch(`http://127.0.0.1:5001/demo-lokasyon/us-central1/${name}`,{method:'POST',headers:{'content-type':'application/json',...(user?{authorization:`Bearer ${user.token}`}:{})},body:JSON.stringify({data})});return {status:r.status,body:await r.json()};}
async function op(user,org,kind,args,id=crypto.randomUUID()){return call('businessOperation',user,{org,kind,args,id});}
function success(response){assert.equal(response.status,200,JSON.stringify(response.body));return response.body.result;}
test('mutations serveur : isolation, calculs, stock concurrent, paiements et reçus autoritaires',async()=>{
 const owner=await account('owner'),other=await account('other'),employee=await account('employee'),org=owner.uid;
 await db.doc(`organizations/${org}`).set({organizationId:org,status:'active'});for(const [u,role] of [[owner,'admin'],[employee,'employee']])await db.doc(`organizations/${org}/users/${u.uid}`).set({organizationId:org,role});
 const input={assetId:'BIEN-00003',customerId:'CLI-00001',quantity:2,start:'2026-10-07T10:00:00Z',end:'2026-10-08T10:00:00Z',rate:12.5,unit:'jour',currency:'HTG',paid:5,method:'Cash HTG'};
 assert.equal((await op(null,org,'seed',[])).body.error.status,'UNAUTHENTICATED');assert.equal((await op(other,org,'seed',[])).body.error.status,'PERMISSION_DENIED');assert.equal((await op(employee,org,'saveRow',['settings',{name:'forged'},'company'])).body.error.status,'PERMISSION_DENIED');success(await op(owner,org,'seed',[]));
 const asset=success(await op(owner,org,'saveRow',['assets',{name:'Bien neuf',quantity:2,available:999,rate:10,deposit:0,categoryId:'CAT-3',currency:'HTG',unit:'jour',status:'Disponible'}]));assert.equal((await db.doc(`organizations/${org}/assets/${asset}`).get()).data().available,2);
 const stockRace=await Promise.all([op(employee,org,'createRental',[{...input,assetId:asset,quantity:2,paid:0}]),op(employee,org,'createRental',[{...input,assetId:asset,quantity:2,paid:0}])]);assert.equal(stockRace.filter(r=>r.status===200).length,1);assert.equal((await db.doc(`organizations/${org}/assets/${asset}`).get()).data().available,0);
 const id=crypto.randomUUID();const replies=await Promise.all([op(employee,org,'createRental',[{...input,total:1,balance:0}],id),op(employee,org,'createRental',[{...input,total:1,balance:0}],id)]);const rentalId=success(replies[0]);assert.equal(success(replies[1]),rentalId);const rental=db.doc(`organizations/${org}/rentals/${rentalId}`);assert.equal((await rental.get()).data().total,25);assert.equal((await db.doc(`organizations/${org}/assets/BIEN-00003`).get()).data().available,8);
 assert.equal((await op(employee,org,'createRental',[{...input,quantity:3}],id)).body.error.status,'ALREADY_EXISTS');assert.equal((await op(employee,org,'createRental',[{...input,quantity:100}])).body.error.status,'INVALID_ARGUMENT');
 const paymentId=crypto.randomUUID();success(await op(employee,org,'pay',[rentalId,10,'Cash HTG'],paymentId));success(await op(employee,org,'pay',[rentalId,10,'Cash HTG'],paymentId));assert.equal((await rental.get()).data().paid,15);assert.equal((await op(employee,org,'pay',[rentalId,11,'Cash HTG'])).body.error.status,'INVALID_ARGUMENT');assert.equal((await op(employee,org,'pay',[rentalId,-1,'Cash HTG'])).body.error.status,'INVALID_ARGUMENT');
 const race=await Promise.all([op(employee,org,'pay',[rentalId,10,'Cash HTG']),op(employee,org,'pay',[rentalId,10,'Cash HTG'])]);assert.equal(race.filter(r=>r.status===200).length,1);assert.equal((await rental.get()).data().balance,0);
 const receipt=(await db.doc(`organizations/${org}/offlineOperations/${paymentId}`).get()).data();assert.equal(receipt.createdBy,employee.uid);assert.match(receipt.signature,/^[a-f0-9]{64}$/);assert.equal((await op(owner,org,'pay',[rentalId,10,'Cash HTG'],paymentId)).body.error.status,'ALREADY_EXISTS');
 await db.doc(`accountStatus/${employee.uid}`).set({disabled:true});assert.equal((await op(employee,org,'pay',[rentalId,1,'Cash HTG'])).body.error.status,'PERMISSION_DENIED');await db.doc(`accountStatus/${employee.uid}`).delete();
 success(await op(employee,org,'returnRental',[rentalId,{actualReturn:new Date().toISOString(),returnState:'Bon état',penalties:0,damageFees:0,returnNotes:''}]));assert.equal((await db.doc(`organizations/${org}/assets/BIEN-00003`).get()).data().available,10);assert.equal((await op(employee,org,'returnRental',[rentalId,{actualReturn:new Date().toISOString(),returnState:'Bon état',penalties:0}])).body.error.status,'INVALID_ARGUMENT');assert((await db.collection(`organizations/${org}/businessAudit`).get()).size>=5);
});
test('photos privées : décodage réel, absence de jeton public, refus étranger et suspension',async()=>{
 const owner=await account('photo'),other=await account('photo-other'),org=owner.uid;await db.doc(`organizations/${org}`).set({organizationId:org,status:'active'});await db.doc(`organizations/${org}/users/${org}`).set({organizationId:org,role:'admin'});
 const png=await sharp({create:{width:2,height:2,channels:3,background:'#123456'}}).png().toBuffer();const path=success(await call('uploadPrivatePhoto',owner,{org,data:png.toString('base64')}));assert(path.startsWith(`organizations/${org}/private/`));const [metadata]=await getStorage().bucket().file(path).getMetadata();assert(!metadata.metadata?.firebaseStorageDownloadTokens);
 assert.equal((await call('uploadPrivatePhoto',owner,{org,data:Buffer.from('<svg/>').toString('base64')})).body.error.status,'INVALID_ARGUMENT');assert.equal((await call('readPrivatePhoto',other,{org,path})).body.error.status,'PERMISSION_DENIED');assert.equal((await call('readPrivatePhoto',null,{org,path})).body.error.status,'UNAUTHENTICATED');assert.equal(success(await call('readPrivatePhoto',owner,{org,path})).contentType,'image/jpeg');
 const response=await fetch(`http://127.0.0.1:9199/v0/b/demo-lokasyon.appspot.com/o/${encodeURIComponent(path)}?alt=media`);assert([401,403].includes(response.status),`Anonymous media returned ${response.status}`);
 await db.doc(`organizations/${org}`).update({status:'suspended'});assert.equal((await call('readPrivatePhoto',owner,{org,path})).body.error.status,'PERMISSION_DENIED');await db.doc(`superAdmins/${other.uid}`).set({active:true});assert.equal(success(await call('readPrivatePhoto',other,{org,path})).contentType,'image/jpeg');await db.doc(`accountStatus/${other.uid}`).set({disabled:true});assert.equal((await call('readPrivatePhoto',other,{org,path})).body.error.status,'PERMISSION_DENIED');
});
