import {test,before,after,beforeEach} from 'node:test';
import {readFileSync} from 'node:fs';
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import {doc,setDoc,getDoc,getDocs,collection,updateDoc,deleteDoc,writeBatch} from 'firebase/firestore';
import {ref,uploadBytes,getBytes} from 'firebase/storage';
let env;
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-lokasyon',firestore:{host:'127.0.0.1',port:8080,rules:readFileSync('firestore.rules','utf8')},storage:{host:'127.0.0.1',port:9199,rules:readFileSync('storage.rules','utf8')}});});
after(async()=>{await env?.cleanup();});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await Promise.all([
 setDoc(doc(db,'organizations','owner'),{organizationId:'owner',name:'Entreprise',status:'active'}),
 setDoc(doc(db,'organizations','owner','users','owner'),{organizationId:'owner',role:'admin',email:'owner@example.com'}),
 setDoc(doc(db,'organizations','owner','users','employee'),{organizationId:'owner',role:'employee',email:'employee@example.com'}),
 setDoc(doc(db,'organizations','owner','customers','CLI-1'),{organizationId:'owner',firstName:'Jean'}),
 setDoc(doc(db,'organizations','other'),{organizationId:'other',name:'Autre',status:'active'}),
 setDoc(doc(db,'superAdmins','super'),{active:true,email:'super@example.com'}),
 setDoc(doc(db,'adminAudit','event'),{actor:'super',action:'test',target:'owner'}),
 ]);});});
test('un administrateur d’entreprise ne peut pas se promouvoir ni administrer la plateforme',async()=>{const db=env.authenticatedContext('owner').firestore();await assertFails(setDoc(doc(db,'superAdmins','owner'),{active:true}));await assertFails(setDoc(doc(db,'platform','settings'),{maintenance:true}));await assertFails(setDoc(doc(db,'adminAudit','forged'),{actor:'owner'}));await assertFails(getDocs(collection(db,'organizations')));await assertFails(getDoc(doc(db,'organizations','other')));});
test('le propriétaire ne peut pas contourner la suspension par une modification de son entreprise',async()=>{const db=env.authenticatedContext('owner').firestore();await assertSucceeds(updateDoc(doc(db,'organizations','owner'),{name:'Nouveau nom'}));await assertFails(updateDoc(doc(db,'organizations','owner'),{status:'suspended'}));await env.withSecurityRulesDisabled(c=>updateDoc(doc(c.firestore(),'organizations','owner'),{status:'suspended'}));await assertFails(updateDoc(doc(db,'organizations','owner'),{status:'active'}));await assertFails(getDoc(doc(db,'organizations','owner','customers','CLI-1')));});
test('un employé lit les données métier sans accéder aux fonctions administratives',async()=>{const db=env.authenticatedContext('employee').firestore();await assertSucceeds(getDoc(doc(db,'organizations','owner','customers','CLI-1')));await assertFails(setDoc(doc(db,'organizations','owner','settings','company'),{organizationId:'owner',name:'Intrusion'}));await assertFails(getDoc(doc(db,'adminAudit','event')));});
test('la suspension d’un membre bloque son accès à l’entreprise',async()=>{const db=env.authenticatedContext('employee').firestore();await assertSucceeds(getDoc(doc(db,'organizations','owner','customers','CLI-1')));await env.withSecurityRulesDisabled(c=>updateDoc(doc(c.firestore(),'organizations','owner','users','employee'),{disabled:true}));await assertFails(getDoc(doc(db,'organizations','owner','customers','CLI-1')));});
test('la suspension d’un compte bloque les jetons déjà ouverts',async()=>{const db=env.authenticatedContext('owner').firestore();await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'accountStatus','owner'),{disabled:true}));await assertFails(getDoc(doc(db,'organizations','owner','customers','CLI-1')));await assertFails(setDoc(doc(db,'accountStatus','owner'),{disabled:false}));});
test('la maintenance bloque les comptes ordinaires tout en préservant le contrôle global',async()=>{await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'platform','settings'),{maintenance:true}));await assertFails(getDoc(doc(env.authenticatedContext('owner').firestore(),'organizations','owner','customers','CLI-1')));await assertSucceeds(getDoc(doc(env.authenticatedContext('super').firestore(),'organizations','owner','customers','CLI-1')));});
test('la fermeture des inscriptions interdit la création d’une entreprise par SDK direct',async()=>{await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'platform','settings'),{registrationOpen:false}));await assertFails(setDoc(doc(env.authenticatedContext('new').firestore(),'organizations','new'),{organizationId:'new',name:'Interdit',status:'active'}));});
test('un super-admin peut lire toutes les entreprises et les audits, mais les écritures globales passent par le serveur',async()=>{const db=env.authenticatedContext('super').firestore();await assertSucceeds(getDocs(collection(db,'organizations')));await assertSucceeds(getDoc(doc(db,'adminAudit','event')));await assertFails(setDoc(doc(db,'superAdmins','another'),{active:true}));await assertFails(updateDoc(doc(db,'organizations','owner'),{status:'suspended'}));});
test('les membres ne peuvent pas obtenir un rôle global et le propriétaire ne peut pas être rétrogradé',async()=>{const db=env.authenticatedContext('owner').firestore();await assertSucceeds(setDoc(doc(db,'organizations','owner','users','new-member'),{organizationId:'owner',role:'employee',email:'new@example.com'}));await assertFails(setDoc(doc(db,'organizations','owner','users','attacker'),{organizationId:'owner',role:'superadmin',email:'bad@example.com'}));await assertFails(updateDoc(doc(db,'organizations','owner','users','owner'),{role:'employee'}));});
test('les règles Storage appliquent également les suspensions et le type des fichiers',async()=>{const storage=env.authenticatedContext('owner').storage();const photo=ref(storage,'organizations/owner/test.png');await assertSucceeds(uploadBytes(photo,new Uint8Array([1,2,3]),{contentType:'image/png'}));await assertFails(uploadBytes(ref(storage,'organizations/owner/script.txt'),new Uint8Array([1]),{contentType:'text/plain'}));await env.withSecurityRulesDisabled(c=>updateDoc(doc(c.firestore(),'organizations','owner'),{status:'suspended'}));await assertFails(getBytes(photo));await assertFails(uploadBytes(photo,new Uint8Array([1]),{contentType:'image/png'}));await assertSucceeds(getBytes(ref(env.authenticatedContext('super').storage(),'organizations/owner/test.png')));});

test('les pro forma restent isolées, sans paiement et protégées après conversion ou annulation',async()=>{
 const db=env.authenticatedContext('employee').firestore(),target=doc(db,'organizations','owner','proformas','PF-1');
 const quote={organizationId:'owner',quantity:2,currency:'HTG',paid:0,status:'Brouillon',createdAt:'2026-10-06'};
 await assertFails(setDoc(target,{...quote,paid:100}));await assertFails(setDoc(target,{...quote,status:'Convertie'}));
 await assertSucceeds(setDoc(target,quote));await assertFails(getDoc(doc(env.authenticatedContext('other').firestore(),'organizations','owner','proformas','PF-1')));
 await assertFails(updateDoc(target,{status:'Convertie',rentalId:'LOC-1',invoiceId:'FAC-1',convertedAt:'now'}));
 const batch=writeBatch(db);batch.set(doc(db,'organizations','owner','rentals','LOC-1'),{organizationId:'owner',proformaId:'PF-1'});batch.set(doc(db,'organizations','owner','invoices','FAC-1'),{organizationId:'owner',rentalId:'LOC-1'});batch.update(target,{status:'Convertie',rentalId:'LOC-1',invoiceId:'FAC-1',convertedAt:'now'});await assertSucceeds(batch.commit());
 await assertFails(updateDoc(target,{quantity:3}));await assertFails(deleteDoc(doc(env.authenticatedContext('owner').firestore(),'organizations','owner','proformas','PF-1')));
 const cancelled=doc(db,'organizations','owner','proformas','PF-2');await assertSucceeds(setDoc(cancelled,quote));await assertSucceeds(updateDoc(cancelled,{status:'Annulée'}));await assertFails(updateDoc(cancelled,{status:'Brouillon'}));
});
test('la comptabilité est réservée aux admins et ses écritures passent uniquement par le serveur',async()=>{
 await env.withSecurityRulesDisabled(async c=>{for(const name of ['accountingAccounts','accountingEntries','accountingPeriods','accountingAudit','accountingSources'])await setDoc(doc(c.firestore(),'organizations','owner',name,'test'),{organizationId:'owner',date:'2026-10-06'});});
 const owner=env.authenticatedContext('owner').firestore(),employee=env.authenticatedContext('employee').firestore();
 for(const name of ['accountingAccounts','accountingEntries','accountingPeriods','accountingAudit','accountingSources']){const target=doc(owner,'organizations','owner',name,'test');await assertSucceeds(getDoc(target));await assertFails(getDoc(doc(employee,'organizations','owner',name,'test')));await assertFails(getDoc(doc(env.authenticatedContext('other').firestore(),'organizations','owner',name,'test')));await assertFails(setDoc(target,{organizationId:'owner'}));await assertFails(deleteDoc(target));}
 await assertFails(setDoc(doc(owner,'organizations','owner','counters','accountingJournal'),{organizationId:'owner',value:999}));await assertSucceeds(getDoc(doc(env.authenticatedContext('super').firestore(),'organizations','owner','accountingEntries','test')));
});
test('les reçus de synchronisation sont personnels, immuables et soumis aux suspensions',async()=>{
 const db=env.authenticatedContext('owner').firestore(),target=doc(db,'organizations','owner','offlineOperations','unique');const receipt={organizationId:'owner',createdBy:'owner',createdAt:'2026-10-07',kind:'pay',result:null};
 await assertSucceeds(getDoc(target));await assertFails(setDoc(target,{...receipt,createdBy:'employee'}));await assertSucceeds(setDoc(target,receipt));await assertFails(updateDoc(target,{result:'changed'}));await assertFails(deleteDoc(target));await assertFails(getDoc(doc(env.authenticatedContext('employee').firestore(),'organizations','owner','offlineOperations','unique')));await assertFails(getDoc(doc(env.authenticatedContext('other').firestore(),'organizations','owner','offlineOperations','unique')));await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'accountStatus','owner'),{disabled:true}));await assertFails(setDoc(doc(db,'organizations','owner','offlineOperations','suspended'),receipt));
});
